# -*- coding: utf-8 -*-
"""Menu Osteria Tre Gobbi — edizione lug/ago/set 2026.
Traduzioni EN / FR / ES / DE / UK, revisionate da madrelingua.

STRUTTURA
  PIATTI       lista di dict, uno per piatto, nell'ordine della carta.
               Chiave di aggancio: it.titolo (titolo italiano esatto).
               Campi: sezione, prezzo, it/en/fr/es/de/uk -> {titolo, descrizione}
               descrizione = None dove il piatto non ne ha (voci senza testo).
  DEGUSTAZIONI lista di dict: nome, sottotitolo, intro, note, prezzo, steps.
  TESTI        blocchi non legati a un piatto: storia, etichette di sezione,
               menu bambini, bevande, note allergeni.
  LINGUE       ("it", "en", "fr", "es", "de", "uk") — "it" e' la lingua madre.

NOTE PER IL SEED
  - Il match va fatto su it.titolo normalizzato (trim, casefold, apostrofi
    tipografici uniformati). Le righe non abbinate vanno stampate a video.
  - I tag allergeni fanno parte del titolo: (NG)/(NL) in italiano, (GF)/(LF)
    in inglese e tedesco, (SG)/(SL) in francese e spagnolo, (БГ)/(БЛ) in ucraino.
  - Il francese contiene spazi insecabili U+00A0 prima di : ; ! ? e nei « ».
  - <i>...</i> compare in alcuni testi narrativi: e' corsivo, non HTML da fuggire.
"""

LINGUE = ("it", "en", "fr", "es", "de", "uk")

PIATTI = [
    # ── antipasti ─────────────────────────────────────────────────
    {
        "sezione": "antipasti",
        "prezzo": "16",
        "it": {"titolo": "PARMIGIANA DI ZUCCHINE E MELANZANE",
               "descrizione": "Cotta al forno con zucchine e melanzane, salsa ai tre pomodori, parmigiano e crema di zucchine alla menta."},
        "en": {"titolo": "COURGETTE AND AUBERGINE PARMIGIANA",
               "descrizione": "Baked with courgettes and aubergines, a three-tomato sauce, Parmigiano and a minted courgette cream."},
        "fr": {"titolo": "PARMIGIANA DE COURGETTES ET AUBERGINES",
               "descrizione": "Cuite au four avec des courgettes et des aubergines, sauce aux trois tomates, parmesan et crème de courgette à la menthe."},
        "es": {"titolo": "PARMIGIANA DE CALABACÍN Y BERENJENA",
               "descrizione": "Al horno con calabacín y berenjena, salsa de tres tomates, parmesano y crema de calabacín a la menta."},
        "de": {"titolo": "PARMIGIANA AUS ZUCCHINI UND AUBERGINEN",
               "descrizione": "Im Ofen gebacken mit Zucchini und Auberginen, Sauce aus drei Tomatensorten, Parmigiano und Zucchinicreme mit Minze."},
        "uk": {"titolo": "ПАРМІДЖАНА З КАБАЧКІВ І БАКЛАЖАНІВ",
               "descrizione": "Запечена в духовці з кабачками й баклажанами, соус із трьох сортів помідорів, пармезан і крем із кабачків із м’ятою."},
    },
    {
        "sezione": "antipasti",
        "prezzo": "16",
        "it": {"titolo": "CARPACCIO DI POMODORO CUORE DI BUE",
               "descrizione": "Pomodoro cuore di bue affettato sottile, burratina a pezzi, origano, acciuga del Cantabrico e capperi fritti."},
        "en": {"titolo": "OXHEART TOMATO CARPACCIO",
               "descrizione": "Oxheart tomato sliced thin, torn burratina, oregano, Cantabrian anchovy and fried capers."},
        "fr": {"titolo": "CARPACCIO DE TOMATE CŒUR DE BŒUF",
               "descrizione": "Tomate cœur de bœuf finement tranchée, burratina en morceaux, origan, anchois du Cantabrique et câpres frites."},
        "es": {"titolo": "CARPACCIO DE TOMATE CORAZÓN DE BUEY",
               "descrizione": "Tomate corazón de buey en láminas finas, burratina en trozos, orégano, anchoa del Cantábrico y alcaparras fritas."},
        "de": {"titolo": "CARPACCIO VON DER OCHSENHERZTOMATE",
               "descrizione": "Dünn aufgeschnittene Ochsenherztomate, Burratina in Stücken, Oregano, Sardellen aus dem Kantabrischen Meer und frittierte Kapern."},
        "uk": {"titolo": "КАРПАЧО З ПОМІДОРА «БИЧАЧЕ СЕРЦЕ»",
               "descrizione": "Тонко нарізаний помідор «бичаче серце», шматочки бурратини, орегано, кантабрійський анчоус і смажені каперси."},
    },
    {
        "sezione": "antipasti",
        "prezzo": "16",
        "it": {"titolo": "CAPPUCCINO DI BACCALÀ E PATATA",
               "descrizione": "Baccalà mantecato alla veneziana, spuma di patata affumicata e polvere di bottarga."},
        "en": {"titolo": "BACCALÀ AND POTATO “CAPPUCCINO”",
               "descrizione": "Venetian-style whipped salt cod, smoked potato foam and bottarga powder."},
        "fr": {"titolo": "« CAPPUCCINO » DE BACCALÀ ET POMME DE TERRE",
               "descrizione": "Baccalà mantecato à la vénitienne, espuma de pomme de terre fumée et poudre de poutargue."},
        "es": {"titolo": "«CAPUCHINO» DE BACALAO Y PATATA",
               "descrizione": "Bacalao mantecado a la veneciana, espuma de patata ahumada y polvo de botarga."},
        "de": {"titolo": "„CAPPUCCINO“ VON BACCALÀ UND KARTOFFEL",
               "descrizione": "Baccalà mantecato nach venezianischer Art, Schaum von geräucherter Kartoffel und Bottarga-Pulver."},
        "uk": {"titolo": "«КАПУЧИНО» З BACCALÀ ТА КАРТОПЛІ",
               "descrizione": "Baccalà mantecato по-венеційськи, піна з копченої картоплі та порошок із ботарги."},
    },
    {
        "sezione": "antipasti",
        "prezzo": "16",
        "it": {"titolo": "COZZE IN BLU",
               "descrizione": "Cozze appena scottate al forno, fonduta leggera di Strachitunt, limone sotto sale ed olio al prezzemolo."},
        "en": {"titolo": "MUSSELS IN BLUE",
               "descrizione": "Mussels flashed in the oven, a light Strachitunt fondue, preserved lemon and parsley oil."},
        "fr": {"titolo": "MOULES EN BLEU",
               "descrizione": "Moules à peine saisies au four, fondue légère de Strachitunt, citron confit au sel et huile de persil."},
        "es": {"titolo": "MEJILLONES EN AZUL",
               "descrizione": "Mejillones apenas pasados por el horno, fondue ligera de Strachitunt, limón en salazón y aceite de perejil."},
        "de": {"titolo": "MIESMUSCHELN IN BLAU",
               "descrizione": "Kurz im Ofen überbackene Miesmuscheln, leichtes Fondue vom Strachitunt, Salzzitrone und Petersilienöl."},
        "uk": {"titolo": "МІДІЇ В БЛАКИТНОМУ",
               "descrizione": "Мідії, ледь припечені в духовці, легке фондю зі стракітунта, лимон у солі та олія з петрушки."},
    },
    {
        "sezione": "antipasti",
        "prezzo": "16",
        "it": {"titolo": "SUA MAESTÀ “LA TARAGNA”",
               "descrizione": "Polenta cotta lentamente con burro, salvia e cinque formaggi bergamaschi: taleggio, stracchino, formai de mut, branzi e formagella."},
        "en": {"titolo": "HER MAJESTY “LA TARAGNA”",
               "descrizione": "Polenta cooked slowly with butter, sage and five Bergamasque cheeses: Taleggio, Stracchino, Formai de Mut, Branzi and Formagella."},
        "fr": {"titolo": "SA MAJESTÉ « LA TARAGNA »",
               "descrizione": "Polenta longuement cuite au beurre et à la sauge avec cinq fromages bergamasques : Taleggio, Stracchino, Formai de Mut, Branzi et Formagella."},
        "es": {"titolo": "SU MAJESTAD «LA TARAGNA»",
               "descrizione": "Polenta cocida despacio con mantequilla, salvia y cinco quesos bergamascos: Taleggio, Stracchino, Formai de Mut, Branzi y Formagella."},
        "de": {"titolo": "IHRE MAJESTÄT „LA TARAGNA“",
               "descrizione": "Langsam gekochte Polenta mit Butter, Salbei und fünf Bergamasker Käsesorten: Taleggio, Stracchino, Formai de Mut, Branzi und Formagella."},
        "uk": {"titolo": "ЇЇ ВЕЛИЧНІСТЬ «ЛА ТАРАНЬЯ»",
               "descrizione": "Полента, повільно зварена на вершковому маслі з шавлією та п’ятьма бергамськими сирами: таледжо, стракіно, формай де мут, брандзі й формаджелла."},
    },
    {
        "sezione": "antipasti",
        "prezzo": "22",
        "it": {"titolo": "BATTUTA DI MANZO E COCOMERO",
               "descrizione": "Manzo 100% italiano condito per bene, anguria compressa, pomodoro e dripping di sapori."},
        "en": {"titolo": "HAND-CUT BEEF TARTARE AND WATERMELON",
               "descrizione": "100% Italian beef, well seasoned, pressed watermelon, tomato and drips of flavour across the plate."},
        "fr": {"titolo": "TARTARE DE BŒUF ET PASTÈQUE",
               "descrizione": "Bœuf 100 % italien bien assaisonné, pastèque pressée, tomate et des traits de saveurs façon dripping."},
        "es": {"titolo": "TARTAR DE VACUNO Y SANDÍA",
               "descrizione": "Carne de vacuno 100 % italiana, bien aliñada, sandía prensada, tomate y un dripping de sabores."},
        "de": {"titolo": "TATAR VOM RIND UND WASSERMELONE",
               "descrizione": "Rindfleisch, 100 % italienisch, kräftig gewürzt, gepresste Wassermelone, Tomate und ein Dripping aus Aromen."},
        "uk": {"titolo": "ТАРТАР ІЗ ЯЛОВИЧИНИ З КАВУНОМ",
               "descrizione": "Яловичина, 100 % італійська, добре приправлена, пресований кавун, помідор і дрипінг зі смаків."},
    },
    {
        "sezione": "antipasti",
        "prezzo": "22",
        "it": {"titolo": "IL VITELLO TONNATO DELL’OSTERIA",
               "descrizione": "Spuma di salsa tonnata fresca, fondo bruno e capperi su un meraviglioso girello di vitello cotto al punto rosa. Ispirato da Diego Rossi, e a lui dedicato."},
        "en": {"titolo": "THE OSTERIA’S VITELLO TONNATO",
               "descrizione": "Fresh tuna-sauce foam, brown jus and capers over a beautiful eye round of veal cooked blushing pink. Inspired by Diego Rossi, and dedicated to him."},
        "fr": {"titolo": "LE VITELLO TONNATO DE L’OSTERIA",
               "descrizione": "Espuma de sauce au thon toute fraîche, fond brun et câpres sur un magnifique rond de gîte de veau cuit rosé. Inspiré par Diego Rossi, et qui lui est dédié."},
        "es": {"titolo": "EL VITELLO TONNATO DE LA OSTERIA",
               "descrizione": "Espuma de salsa de atún recién hecha, fondo oscuro y alcaparras sobre un espléndido redondo de ternera cocinado al punto rosa. Inspirado en Diego Rossi, y dedicado a él."},
        "de": {"titolo": "UNSER VITELLO TONNATO",
               "descrizione": "Schaum von frischer Thunfischsauce, brauner Jus und Kapern auf einer wunderbaren, rosa gegarten Kalbsrolle. Inspiriert von Diego Rossi und ihm gewidmet."},
        "uk": {"titolo": "VITELLO TONNATO НАШОЇ ОСТЕРІЇ",
               "descrizione": "Піна зі свіжого тунцевого соусу, темний м’ясний соус і каперси на чудовому шматку телячого огузка, приготованому до рожевого. Натхнення — Дієго Россі, йому ж і присвячено."},
    },
    {
        "sezione": "antipasti",
        "prezzo": "16",
        "it": {"titolo": "IL SALAME DEL ROBERTO CON LA GIARDINIERA",
               "descrizione": "Il salame che fa il Roberto, stagionato lentamente in cantina e tagliato a fette grosse, accompagnato dalle nostre verdure."},
        "en": {"titolo": "ROBERTO’S SALAME WITH GIARDINIERA",
               "descrizione": "The salame Roberto makes, aged slowly down in the cellar and cut into thick slices, with our own pickled vegetables."},
        "fr": {"titolo": "LE SALAME DE ROBERTO ET SA GIARDINIERA",
               "descrizione": "Le salame que fait Roberto, affiné lentement en cave et coupé en tranches épaisses, accompagné de nos légumes au vinaigre."},
        "es": {"titolo": "EL SALAMI DE ROBERTO CON GIARDINIERA",
               "descrizione": "El salami que hace Roberto, curado despacio en la bodega y cortado en lonchas gruesas, con nuestras verduras en vinagre."},
        "de": {"titolo": "ROBERTOS SALAMI MIT GIARDINIERA",
               "descrizione": "Die Salami von Roberto: langsam im Keller gereift, in dicke Scheiben geschnitten, dazu unser eingelegtes Gemüse."},
        "uk": {"titolo": "САЛЯМІ ВІД РОБЕРТО З ДЖАРДІНЬЄРОЮ",
               "descrizione": "Салямі, яку робить Роберто: повільно визріває в підвалі, нарізана товстими кружальцями, з нашими маринованими овочами."},
    },
    {
        "sezione": "antipasti",
        "prezzo": "20",
        "it": {"titolo": "I SALUMI MISTI DELL’OSTERIA",
               "descrizione": None},
        "en": {"titolo": "THE OSTERIA’S MIXED SALUMI",
               "descrizione": None},
        "fr": {"titolo": "L’ASSIETTE DE SALUMI DE L’OSTERIA",
               "descrizione": None},
        "es": {"titolo": "SURTIDO DE SALUMI DE LA OSTERIA",
               "descrizione": None},
        "de": {"titolo": "UNSERE SALUMI-AUSWAHL",
               "descrizione": None},
        "uk": {"titolo": "НАШЕ АСОРТІ SALUMI",
               "descrizione": None},
    },
    # ── paste_risi_zuppe ──────────────────────────────────────────
    {
        "sezione": "paste_risi_zuppe",
        "prezzo": "18",
        "it": {"titolo": "RISOTTO ALL’ALBICOCCA, AGRÌ DI VALTORTA, MANDORLE E VERMOUTH",
               "descrizione": "Carnaroli riserva “San Massimo”, albicocca fresca e cotta nel vermouth, mantecato all’agrì di Valtorta Presidio Slow Food e finito con un crumble alla mandorla."},
        "en": {"titolo": "RISOTTO WITH APRICOT, AGRÌ DI VALTORTA, ALMOND AND VERMOUTH",
               "descrizione": "Carnaroli “San Massimo” Riserva rice, apricot both fresh and cooked in vermouth, stirred through with Agrì di Valtorta — a Slow Food Presidium cheese — and finished with an almond crumble."},
        "fr": {"titolo": "RISOTTO À L’ABRICOT, AGRÌ DI VALTORTA, AMANDES ET VERMOUTH",
               "descrizione": "Carnaroli riserva « San Massimo », abricot frais et cuit au vermouth, monté à l’agrì di Valtorta — sentinelle Slow Food — et fini d’un crumble d’amande."},
        "es": {"titolo": "RISOTTO DE ALBARICOQUE, AGRÌ DI VALTORTA, ALMENDRA Y VERMUT",
               "descrizione": "Carnaroli riserva «San Massimo», albaricoque fresco y cocido en vermut, mantecado con agrì di Valtorta —Baluarte Slow Food— y terminado con un crumble de almendra."},
        "de": {"titolo": "RISOTTO MIT APRIKOSE, AGRÌ DI VALTORTA, MANDELN UND WERMUT",
               "descrizione": "Carnaroli riserva „San Massimo“, Aprikose frisch und in Wermut gegart, mit Agrì di Valtorta – einem Slow-Food-Presidio-Käse – montiert und mit Mandelcrumble vollendet."},
        "uk": {"titolo": "РИЗОТО З АБРИКОСОМ, АГРІ ДІ ВАЛЬТОРТА, МИГДАЛЕМ І ВЕРМУТОМ",
               "descrizione": "Карнаролі riserva «San Massimo», абрикос свіжий і томлений у вермуті, вимішаний із сиром агрі ді Вальторта (Presidio Slow Food) і завершений мигдалевим крамблом."},
    },
    {
        "sezione": "paste_risi_zuppe",
        "prezzo": "18",
        "it": {"titolo": "FETTUCCINE ALL’ALFREDO SE FOSSE NATO A BERGAMO",
               "descrizione": "Pasta fresca mantecata al burro e formai de mut DOP: se le provi, non le dimentichi."},
        "en": {"titolo": "FETTUCCINE ALL’ALFREDO, HAD ALFREDO BEEN BORN IN BERGAMO",
               "descrizione": "Fresh pasta stirred through butter and Formai de Mut DOP: taste them once and you won’t forget them."},
        "fr": {"titolo": "FETTUCCINE ALL’ALFREDO, SI ALFREDO ÉTAIT NÉ À BERGAME",
               "descrizione": "Pâtes fraîches montées au beurre et au formai de mut DOP : si vous les goûtez, vous ne les oublierez pas."},
        "es": {"titolo": "FETTUCCINE ALL’ALFREDO SI ALFREDO HUBIERA NACIDO EN BÉRGAMO",
               "descrizione": "Pasta fresca mantecada con mantequilla y formai de mut DOP: si las pruebas, no las olvidas."},
        "de": {"titolo": "FETTUCCINE ALL’ALFREDO, WÄRE ALFREDO IN BERGAMO GEBOREN",
               "descrizione": "Frische Pasta mit Butter und Formai de Mut DOP montiert: einmal probiert, nie wieder vergessen."},
        "uk": {"titolo": "FETTUCCINE ALL’ALFREDO, ЯКБИ АЛЬФРЕДО НАРОДИВСЯ В БЕРГАМО",
               "descrizione": "Свіжа паста, вимішана з вершковим маслом і сиром формай де мут DOP: спробуєте — не забудете."},
    },
    {
        "sezione": "paste_risi_zuppe",
        "prezzo": "18",
        "it": {"titolo": "CASONCELLI DI MAMMA E PAPÀ",
               "descrizione": "Sono proprio i genitori del nostro oste Marco: Antonella e Gerry che ogni giorno ci preparano questa leccornia con la ricetta della nostra famiglia."},
        "en": {"titolo": "MAMMA AND PAPÀ’S CASONCELLI",
               "descrizione": "Bergamo’s own filled pasta. They really are the parents of our oste Marco: Antonella and Gerry, who make us this delicacy every day with our family recipe."},
        "fr": {"titolo": "LES CASONCELLI DE MAMAN ET PAPA",
               "descrizione": "Les raviolis de Bergame. Ce sont vraiment les parents de notre oste Marco : Antonella et Gerry, qui nous préparent chaque jour cette gourmandise avec la recette de la famille."},
        "es": {"titolo": "LOS CASONCELLI DE MAMÁ Y PAPÁ",
               "descrizione": "La pasta rellena de Bérgamo. Son de verdad los padres de nuestro oste Marco: Antonella y Gerry, que cada día nos preparan esta delicia con la receta de la familia."},
        "de": {"titolo": "CASONCELLI VON MAMMA UND PAPÀ",
               "descrizione": "Die gefüllte Pasta Bergamos. Es sind wirklich die Eltern unseres <i>Oste</i> Marco: Antonella und Gerry, die uns diese Köstlichkeit jeden Tag nach dem Familienrezept zubereiten."},
        "uk": {"titolo": "CASONCELLI МАМИ Й ТАТА",
               "descrizione": "Фарширована паста, гордість Бергамо. Це справді батьки нашого oste Марка: Антонелла і Джеррі, які щодня готують нам цю смакоту за родинним рецептом."},
    },
    {
        "sezione": "paste_risi_zuppe",
        "prezzo": "20",
        "it": {"titolo": "FUSILLONI AL SALMÌ DI LEPRE E BRANZI",
               "descrizione": "Fusillone Mancini condito con un sugo di lepre cotto lentamente con Valcalepio, ginepro, cannella ed anice stellato. Il tutto finito con una grattugiata generosa di Branzi giovane a mantecare."},
        "en": {"titolo": "FUSILLONI WITH HARE SALMÌ AND BRANZI",
               "descrizione": "Mancini fusillone in a hare sauce cooked slowly with Valcalepio wine, juniper, cinnamon and star anise, all finished with a generous grating of young Branzi."},
        "fr": {"titolo": "FUSILLONI AU SALMIS DE LIÈVRE ET BRANZI",
               "descrizione": "Fusillone Mancini dans une sauce au lièvre longuement mijotée au Valcalepio, genièvre, cannelle et anis étoilé, le tout lié d’une généreuse râpée de Branzi jeune."},
        "es": {"titolo": "FUSILLONI EN SALMÍ DE LIEBRE Y BRANZI",
               "descrizione": "Fusillone Mancini con una salsa de liebre cocida despacio con Valcalepio, enebro, canela y anís estrellado, todo mantecado con una ralladura generosa de Branzi joven."},
        "de": {"titolo": "FUSILLONI MIT HASEN-SALMÌ UND BRANZI",
               "descrizione": "Fusillone aus dem Pastificio Mancini in einer Hasensauce, langsam geschmort mit Valcalepio-Rotwein, Wacholder, Zimt und Sternanis, zum Schluss großzügig mit jungem Branzi überrieben."},
        "uk": {"titolo": "FUSILLONI З САЛЬМІ ІЗ ЗАЙЦЯ ТА СИРОМ БРАНДЗІ",
               "descrizione": "Fusillone від Mancini із соусом із зайця, повільно тушкованим із вином Валькалепіо, ялівцем, корицею та бадьяном, і завершений щедрою стружкою молодого брандзі."},
    },
    {
        "sezione": "paste_risi_zuppe",
        "prezzo": "45",
        "it": {"titolo": "ZUPPIERA DI PASTA MISTA IN RISTRETTO DI SCOGLIO (prezzo per 2 persone)",
               "descrizione": "Una zuppiera colma di pasta mista cotta in una zuppa ristretta di pesci di scoglio, da mettere in mezzo al tavolo."},
        "en": {"titolo": "A TUREEN OF PASTA MISTA IN ROCKFISH BROTH (price for two)",
               "descrizione": "A tureen brimming with mixed pasta shapes cooked in a reduced rockfish soup, to put in the middle of the table."},
        "fr": {"titolo": "SOUPIÈRE DE PASTA MISTA AU BOUILLON DE POISSONS DE ROCHE (prix pour 2 personnes)",
               "descrizione": "Une soupière débordante de pâtes mélangées cuites dans une soupe de poissons de roche réduite, à poser au milieu de la table."},
        "es": {"titolo": "SOPERA DE PASTA MISTA EN CALDO REDUCIDO DE PESCADO DE ROCA (precio para 2 personas)",
               "descrizione": "Una sopera colmada de pasta mista cocida en una sopa reducida de pescados de roca, para poner en medio de la mesa."},
        "de": {"titolo": "SUPPENTERRINE MIT PASTA MISTA IN FELSENFISCHSUD (Preis für 2 Personen)",
               "descrizione": "Eine randvolle Terrine gemischter Pastasorten, gegart in einer reduzierten Felsenfischsuppe, zum Teilen in der Tischmitte."},
        "uk": {"titolo": "СУПНИЦЯ З PASTA MISTA В НАВАРІ З РИБИ ЗІ СКЕЛЬ (ціна за 2 особи)",
               "descrizione": "Повна супниця з різних видів пасти, звареної в густому наварі з дрібної скельної риби, — на середину столу."},
    },
    {
        "sezione": "paste_risi_zuppe",
        "prezzo": "24",
        "it": {"titolo": "SPAGHETTONI ALLE VONGOLE",
               "descrizione": "Spaghettone del pastificio Mancini cotto in un ristretto di acqua di vongole, prezzemolo ed abbondanti vongole appena aperte a finire."},
        "en": {"titolo": "SPAGHETTONI WITH CLAMS",
               "descrizione": "Spaghettone from the Mancini pasta mill cooked in a reduction of clam liquor and parsley, with plenty of clams opened to order to finish."},
        "fr": {"titolo": "SPAGHETTONI AUX PALOURDES",
               "descrizione": "Spaghettone du pastificio Mancini cuit dans un jus de palourdes réduit avec du persil, et une pluie de palourdes tout juste ouvertes pour finir."},
        "es": {"titolo": "SPAGHETTONI CON ALMEJAS",
               "descrizione": "Spaghettone del pastificio Mancini cocido en un reducido de agua de almejas y perejil, con abundantes almejas recién abiertas para terminar."},
        "de": {"titolo": "SPAGHETTONI MIT VONGOLE",
               "descrizione": "Spaghettone aus dem Pastificio Mancini, gegart in einem reduzierten Vongole-Sud mit Petersilie, zum Schluss reichlich frisch geöffnete Vongole."},
        "uk": {"titolo": "SPAGHETTONI З VONGOLE",
               "descrizione": "Spaghettone від пастифічіо Mancini, зварений у концентрованому відварі з vongole з петрушкою, а насамкінець — щедра порція щойно розкритих мушель."},
    },
    {
        "sezione": "paste_risi_zuppe",
        "prezzo": "18",
        "it": {"titolo": "TEGAMINO DI PACCHERI AI TRE POMODORI",
               "descrizione": "Un godurioso sugo di pomodoro fatto con San Marzano, Pachino e Cuore di Bue a condire i paccheri ben mantecati nel tegamino."},
        "en": {"titolo": "PACCHERI IN THE PAN, THREE-TOMATO SAUCE",
               "descrizione": "A blissful tomato sauce made with San Marzano, Pachino and Cuore di Bue, coating paccheri stirred well in their own pan."},
        "fr": {"titolo": "PACCHERI AU POÊLON, AUX TROIS TOMATES",
               "descrizione": "Une sauce tomate gourmande faite de San Marzano, Pachino et Cœur de Bœuf, pour napper des paccheri bien liés dans leur poêlon."},
        "es": {"titolo": "CAZUELITA DE PACCHERI A LOS TRES TOMATES",
               "descrizione": "Una salsa de tomate golosa hecha con San Marzano, Pachino y Corazón de Buey para napar unos paccheri bien mantecados en su cazuela."},
        "de": {"titolo": "PACCHERI AUS DER PFANNE, DREIERLEI TOMATEN",
               "descrizione": "Eine üppige Tomatensauce aus San Marzano, Pachino und Ochsenherz, dazu in der Pfanne gut montierte Paccheri."},
        "uk": {"titolo": "PACCHERI НА СКОВОРІДЦІ, ТРИ ПОМІДОРИ",
               "descrizione": "Смачнючий томатний соус із San Marzano, Pachino й «бичачого серця», яким огорнуто добре вимішані paccheri просто на сковорідці."},
    },
    # ── piatti_del_giorno ─────────────────────────────────────────
    {
        "sezione": "piatti_del_giorno",
        "prezzo": "da 14 a 26",
        "it": {"titolo": "RACCONTATI A VOCE",
               "descrizione": "Come sulla lavaglia dell’osteria, tutte le idee del giorno con i prodotti migliori in tiratura limitata. Possono finire subito!"},
        "en": {"titolo": "TOLD TO YOU AT THE TABLE",
               "descrizione": "Just like the osteria’s chalkboard: all of today’s ideas with the best produce, in very limited quantities. They can go in minutes!"},
        "fr": {"titolo": "RACONTÉS DE VIVE VOIX",
               "descrizione": "Comme sur l’ardoise de l’osteria, toutes les idées du jour avec les meilleurs produits, en quantité limitée. Elles peuvent partir très vite !"},
        "es": {"titolo": "CONTADOS DE VIVA VOZ",
               "descrizione": "Como en la pizarra de la osteria, todas las ideas del día con los mejores productos, en cantidad limitada. ¡Se pueden acabar enseguida!"},
        "de": {"titolo": "MÜNDLICH ERZÄHLT",
               "descrizione": "Wie auf der Tafel der Osteria: alle Ideen des Tages mit den besten Produkten, in kleiner Menge zubereitet. Diese Gerichte sind oft schnell vergriffen!"},
        "uk": {"titolo": "РОЗКАЖЕМО ВАМ ОСОБИСТО",
               "descrizione": "Як на грифельній дошці остерії — усі ідеї дня з найкращих продуктів, у лімітованій кількості. Можуть закінчитися миттю!"},
    },
    # ── secondi ───────────────────────────────────────────────────
    {
        "sezione": "secondi",
        "prezzo": "26",
        "it": {"titolo": "ANATRA, RIBES E LATTUGA",
               "descrizione": "Petto di anatra in lunga cottura, il suo fondo, crema di ribes in agrodolce, lattuga al forno con nocciole."},
        "en": {"titolo": "DUCK, REDCURRANT AND LETTUCE",
               "descrizione": "Slow-cooked duck breast, its own jus, a sweet-and-sour redcurrant cream, roasted lettuce with hazelnuts."},
        "fr": {"titolo": "CANARD, GROSEILLES ET LAITUE",
               "descrizione": "Filet de canard en cuisson longue, son jus, crème de groseilles à l’aigre-doux, laitue rôtie aux noisettes."},
        "es": {"titolo": "PATO, GROSELLA Y LECHUGA",
               "descrizione": "Pechuga de pato en cocción larga, su fondo, crema agridulce de grosella, lechuga al horno con avellanas."},
        "de": {"titolo": "ENTE, JOHANNISBEERE UND KOPFSALAT",
               "descrizione": "Lange gegarte Entenbrust, ihr eigener Jus, süßsaure Johannisbeercreme, im Ofen gerösteter Kopfsalat mit Haselnüssen."},
        "uk": {"titolo": "КАЧКА, ПОРІЧКИ ТА САЛАТ-ЛАТУК",
               "descrizione": "Качина грудка повільного приготування, власний м’ясний сік, кисло-солодкий крем із порічок, запечений латук із фундуком."},
    },
    {
        "sezione": "secondi",
        "prezzo": "30",
        "it": {"titolo": "ENTRECOTE DI MANZO E FINFERLI",
               "descrizione": "Super taglio di manzo (270/300g) cotto sulla lionese, finito con un fondo bruno e dei finferli al burro."},
        "en": {"titolo": "BEEF ENTRECÔTE AND CHANTERELLES",
               "descrizione": "A serious cut of beef (270/300g) cooked on the griddle, finished with a brown jus and buttered chanterelles."},
        "fr": {"titolo": "ENTRECÔTE DE BŒUF ET GIROLLES",
               "descrizione": "Une belle pièce de bœuf (270/300 g) cuite à la plancha, finie d’un fond brun et de girolles au beurre."},
        "es": {"titolo": "ENTRECOT DE VACUNO Y REBOZUELOS",
               "descrizione": "Un corte generoso de vacuno (270/300 g) hecho a la plancha, terminado con un fondo oscuro y rebozuelos a la mantequilla."},
        "de": {"titolo": "RINDERENTRECÔTE UND PFIFFERLINGE",
               "descrizione": "Ein großzügiges Stück Rind (270/300 g), auf der heißen Grillplatte gegart, vollendet mit braunem Jus und Pfifferlingen in Butter."},
        "uk": {"titolo": "АНТРЕКОТ ІЗ ЯЛОВИЧИНИ ТА ЛИСИЧКИ",
               "descrizione": "Щедрий відруб яловичини (270/300 г) на чавунному грилі, темний м’ясний соус і лисички на вершковому маслі."},
    },
    {
        "sezione": "secondi",
        "prezzo": "26",
        "it": {"titolo": "OSSOBUCO DI VITELLO CON PURÈ",
               "descrizione": "Dalla tradizione lombarda l’ossobuco di vitello lungamente cotto. Servito con la tipica gremolada fatta con prezzemolo, limone e un pizzico di aglio."},
        "en": {"titolo": "VEAL OSSOBUCO WITH MASHED POTATO",
               "descrizione": "From the Lombard tradition, veal ossobuco cooked long and slow. Served with the classic gremolada of parsley, lemon and a hint of garlic."},
        "fr": {"titolo": "OSSOBUCO DE VEAU ET PURÉE",
               "descrizione": "Venu de la tradition lombarde, l’ossobuco de veau longuement cuit. Servi avec la traditionnelle gremolada au persil, citron et une pointe d’ail."},
        "es": {"titolo": "OSSOBUCO DE TERNERA CON PURÉ",
               "descrizione": "De la tradición lombarda, el ossobuco de ternera largamente cocinado. Servido con la típica gremolada de perejil, limón y una pizca de ajo."},
        "de": {"titolo": "OSSOBUCO VOM KALB MIT KARTOFFELPÜREE",
               "descrizione": "Aus der lombardischen Tradition: lange geschmorte Kalbshaxenscheibe. Serviert mit der typischen Gremolada aus Petersilie, Zitrone und einem Hauch Knoblauch."},
        "uk": {"titolo": "ТЕЛЯЧЕ ОСОБУКО З ПЮРЕ",
               "descrizione": "З ломбардської традиції: теляче особуко тривалого томління. Подаємо з класичною гремоладою з петрушки, лимона й дрібки часнику."},
    },
    {
        "sezione": "secondi",
        "prezzo": "35",
        "it": {"titolo": "VUOI UN PIATTO UNICO CON OSSOBUCO E RISOTTO GIALLO?",
               "descrizione": "Opzione per accontentare i più golosi con il piatto completo con risotto milanese e l’ossobuco in gremolada."},
        "en": {"titolo": "FANCY IT ALL ON ONE PLATE, OSSOBUCO AND SAFFRON RISOTTO?",
               "descrizione": "For the greediest among you: the full plate, with risotto alla milanese and the ossobuco in its gremolada."},
        "fr": {"titolo": "ENVIE DU PLAT COMPLET, OSSOBUCO ET RISOTTO SAFRANÉ ?",
               "descrizione": "L’option pour les plus gourmands : l’assiette complète, avec risotto à la milanaise et l’ossobuco en gremolada."},
        "es": {"titolo": "¿QUIERES EL PLATO ÚNICO, OSSOBUCO Y RISOTTO AL AZAFRÁN?",
               "descrizione": "La opción para los más golosos: el plato completo, con risotto a la milanesa y el ossobuco en gremolada."},
        "de": {"titolo": "LIEBER ALLES AUF EINEM TELLER, OSSOBUCO UND SAFRANRISOTTO?",
               "descrizione": "Für die Hungrigsten: der komplette Teller, mit Risotto alla milanese und dem Ossobuco in seiner Gremolada."},
        "uk": {"titolo": "ХОЧЕТЕ ВСЕ В ОДНІЙ ТАРІЛЦІ — ОСОБУКО Й ШАФРАНОВЕ РИЗОТО?",
               "descrizione": "Для найласіших: повна тарілка з ризото по-міланськи й особуко в гремоладі."},
    },
    {
        "sezione": "secondi",
        "prezzo": "24",
        "it": {"titolo": "GUANCETTA DI MAIALINO BRASATA E POLENTA",
               "descrizione": "Cotta 36 ore, tenera e succolenta che profuma di vino e di casa."},
        "en": {"titolo": "BRAISED SUCKLING PIG CHEEK AND POLENTA",
               "descrizione": "Cooked for 36 hours, tender and succulent, with the scent of wine and of home."},
        "fr": {"titolo": "JOUE DE PORCELET BRAISÉE ET POLENTA",
               "descrizione": "Cuite 36 heures, tendre et fondante, elle sent le vin et la maison."},
        "es": {"titolo": "CARRILLERA DE CERDO BRASEADA Y POLENTA",
               "descrizione": "Cocinada 36 horas, tierna y jugosa, huele a vino y a casa."},
        "de": {"titolo": "GESCHMORTE SPANFERKELBACKE UND POLENTA",
               "descrizione": "36 Stunden gegart, zart und saftig, sie duftet nach Wein und nach Zuhause."},
        "uk": {"titolo": "ТУШКОВАНА ЩІЧКА ПОРОСЯТИ Й ПОЛЕНТА",
               "descrizione": "Готується 36 годин: ніжна й соковита, пахне вином і домом."},
    },
    {
        "sezione": "secondi",
        "prezzo": "24",
        "it": {"titolo": "CONIGLIO ALLA BERGAMASCA",
               "descrizione": "Il coniglio come si fa nelle nostre valli: rosolato con pancetta, rosmarino e una sfumata di bianco, finito al forno. Con la polenta nostrana, ovviamente."},
        "en": {"titolo": "RABBIT THE BERGAMO WAY",
               "descrizione": "Rabbit the way they make it up in our valleys: browned with pancetta and rosemary, a splash of white wine, then finished in the oven. With our own polenta, of course."},
        "fr": {"titolo": "LAPIN À LA BERGAMASQUE",
               "descrizione": "Le lapin comme on le fait dans nos vallées : rissolé avec de la pancetta et du romarin, déglacé au vin blanc, fini au four. Avec la polenta maison, évidemment."},
        "es": {"titolo": "CONEJO A LA BERGAMASCA",
               "descrizione": "El conejo como se hace en nuestros valles: dorado con panceta y romero, desglasado con vino blanco y acabado al horno. Con polenta casera, por supuesto."},
        "de": {"titolo": "KANINCHEN AUF BERGAMASKER ART",
               "descrizione": "Kaninchen, wie man es in unseren Tälern macht: mit Pancetta und Rosmarin angebraten, mit Weißwein abgelöscht, im Ofen fertig gegart. Mit Polenta nach Hausart, versteht sich."},
        "uk": {"titolo": "КРОЛИК ПО-БЕРГАМСЬКИ",
               "descrizione": "Кролик так, як його роблять у наших долинах: підсмажений із панчеттою й розмарином, збризнутий білим вином і доведений до готовності в духовці. З домашньою полентою, звісно."},
    },
    {
        "sezione": "secondi",
        "prezzo": "24",
        "it": {"titolo": "SPEZZATINO DI CINGHIALE IN UMIDO",
               "descrizione": "Cinghiale di selezione cotto piano piano in umido con vino rosso ed erbe di montagna. Un sugo che chiede la scarpetta."},
        "en": {"titolo": "WILD BOAR STEW",
               "descrizione": "Selected wild boar, cooked very slowly in red wine with mountain herbs. A sauce that demands a piece of bread to mop it up."},
        "fr": {"titolo": "RAGOÛT DE SANGLIER",
               "descrizione": "Sanglier de sélection, mijoté tout doucement au vin rouge et aux herbes de montagne. Une sauce qui réclame un morceau de pain."},
        "es": {"titolo": "GUISO DE JABALÍ",
               "descrizione": "Jabalí de selección, cocinado muy despacio con vino tinto y hierbas de montaña. Una salsa que pide pan para mojar."},
        "de": {"titolo": "WILDSCHWEINRAGOUT",
               "descrizione": "Ausgewähltes Wildschwein, ganz langsam in Rotwein mit Bergkräutern geschmort. Eine Sauce, die nach einem Stück Brot verlangt."},
        "uk": {"titolo": "РАГУ З ДИКОГО КАБАНА",
               "descrizione": "Відбірний дикий кабан, дуже повільно тушкований у червоному вині з гірськими травами. Соус, який просить хліба."},
    },
    {
        "sezione": "secondi",
        "prezzo": "26",
        "it": {"titolo": "PESCATO DEL GIORNO",
               "descrizione": "Chiedici come l’abbiamo cucinato oggi."},
        "en": {"titolo": "TODAY’S CATCH",
               "descrizione": "Ask us how we have cooked it today."},
        "fr": {"titolo": "POISSON DU JOUR",
               "descrizione": "Demandez-nous comment nous l’avons cuisiné aujourd’hui."},
        "es": {"titolo": "PESCADO DEL DÍA",
               "descrizione": "Pregúntanos cómo lo hemos cocinado hoy."},
        "de": {"titolo": "FANG DES TAGES",
               "descrizione": "Fragen Sie uns, wie wir ihn heute zubereitet haben."},
        "uk": {"titolo": "УЛОВ ДНЯ",
               "descrizione": "Запитайте нас, як ми його приготували сьогодні."},
    },
    # ── contorni ──────────────────────────────────────────────────
    {
        "sezione": "contorni",
        "prezzo": "4",
        "it": {"titolo": "POLENTA NOSTRANA",
               "descrizione": None},
        "en": {"titolo": "OUR OWN POLENTA",
               "descrizione": None},
        "fr": {"titolo": "POLENTA MAISON",
               "descrizione": None},
        "es": {"titolo": "POLENTA CASERA",
               "descrizione": None},
        "de": {"titolo": "POLENTA NACH HAUSART",
               "descrizione": None},
        "uk": {"titolo": "ДОМАШНЯ ПОЛЕНТА",
               "descrizione": None},
    },
    {
        "sezione": "contorni",
        "prezzo": "8",
        "it": {"titolo": "ASSAGGIO DI SUA MAESTÀ LA TARAGNA",
               "descrizione": None},
        "en": {"titolo": "A TASTE OF HER MAJESTY LA TARAGNA",
               "descrizione": None},
        "fr": {"titolo": "UNE BOUCHÉE DE SA MAJESTÉ LA TARAGNA",
               "descrizione": None},
        "es": {"titolo": "UN BOCADO DE SU MAJESTAD LA TARAGNA",
               "descrizione": None},
        "de": {"titolo": "KOSTPROBE VON IHRER MAJESTÄT LA TARAGNA",
               "descrizione": None},
        "uk": {"titolo": "ПОРЦІЯ ЇЇ ВЕЛИЧНОСТІ ЛА ТАРАНЬЇ",
               "descrizione": None},
    },
    {
        "sezione": "contorni",
        "prezzo": "6",
        "it": {"titolo": "PURÈ DI PATATE CREMOSISSIMO",
               "descrizione": None},
        "en": {"titolo": "THE CREAMIEST MASHED POTATO",
               "descrizione": None},
        "fr": {"titolo": "PURÉE DE POMMES DE TERRE ULTRA-CRÉMEUSE",
               "descrizione": None},
        "es": {"titolo": "PURÉ DE PATATA CREMOSÍSIMO",
               "descrizione": None},
        "de": {"titolo": "BESONDERS CREMIGES KARTOFFELPÜREE",
               "descrizione": None},
        "uk": {"titolo": "НАЙНІЖНІШЕ КАРТОПЛЯНЕ ПЮРЕ",
               "descrizione": None},
    },
    {
        "sezione": "contorni",
        "prezzo": "6",
        "it": {"titolo": "PATATE ARROSTO",
               "descrizione": None},
        "en": {"titolo": "ROAST POTATOES",
               "descrizione": None},
        "fr": {"titolo": "POMMES DE TERRE RÔTIES",
               "descrizione": None},
        "es": {"titolo": "PATATAS ASADAS",
               "descrizione": None},
        "de": {"titolo": "RÖSTKARTOFFELN",
               "descrizione": None},
        "uk": {"titolo": "ЗАПЕЧЕНА КАРТОПЛЯ",
               "descrizione": None},
    },
    {
        "sezione": "contorni",
        "prezzo": "6",
        "it": {"titolo": "SPADELLATA DI VERDURE",
               "descrizione": None},
        "en": {"titolo": "PAN-TOSSED VEGETABLES",
               "descrizione": None},
        "fr": {"titolo": "POÊLÉE DE LÉGUMES",
               "descrizione": None},
        "es": {"titolo": "SALTEADO DE VERDURAS",
               "descrizione": None},
        "de": {"titolo": "GEMÜSE AUS DER PFANNE",
               "descrizione": None},
        "uk": {"titolo": "ОВОЧІ НА СКОВОРІДЦІ",
               "descrizione": None},
    },
    {
        "sezione": "contorni",
        "prezzo": "6",
        "it": {"titolo": "GIARDINIERA DI VERDURE",
               "descrizione": None},
        "en": {"titolo": "GIARDINIERA, OUR PICKLED VEGETABLES",
               "descrizione": None},
        "fr": {"titolo": "GIARDINIERA DE LÉGUMES",
               "descrizione": None},
        "es": {"titolo": "GIARDINIERA DE VERDURAS",
               "descrizione": None},
        "de": {"titolo": "GIARDINIERA, EINGELEGTES GEMÜSE",
               "descrizione": None},
        "uk": {"titolo": "ДЖАРДІНЬЄРА, МАРИНОВАНІ ОВОЧІ",
               "descrizione": None},
    },
    {
        "sezione": "contorni",
        "prezzo": "6",
        "it": {"titolo": "INSALATA MISTA DI STAGIONE",
               "descrizione": None},
        "en": {"titolo": "SEASONAL MIXED SALAD",
               "descrizione": None},
        "fr": {"titolo": "SALADE MIXTE DE SAISON",
               "descrizione": None},
        "es": {"titolo": "ENSALADA MIXTA DE TEMPORADA",
               "descrizione": None},
        "de": {"titolo": "GEMISCHTER SAISONSALAT",
               "descrizione": None},
        "uk": {"titolo": "МІШАНИЙ СЕЗОННИЙ САЛАТ",
               "descrizione": None},
    },
    # ── dolci ─────────────────────────────────────────────────────
    {
        "sezione": "dolci",
        "prezzo": "10",
        "it": {"titolo": "LA PIANTINA DEL TIRAMISÙ (NG)",
               "descrizione": "Il nostro dolce più antico in carta dal primo giorno, servito in maniera particolare. Definito da molti il miglior tiramisù mai assaggiato. Non fartelo scappare!"},
        "en": {"titolo": "THE TIRAMISÙ IN A PLANT POT (GF)",
               "descrizione": "Our oldest dessert, on the menu since day one, served in a rather particular way. Many have called it the best tiramisù they have ever eaten. Don’t miss out!"},
        "fr": {"titolo": "LE TIRAMISÙ EN POT DE FLEURS (SG)",
               "descrizione": "Notre dessert le plus ancien, à la carte depuis le premier jour, servi d’une façon bien à lui. Beaucoup disent que c’est le meilleur tiramisù qu’ils aient jamais goûté. Ne le laissez pas filer !"},
        "es": {"titolo": "LA MACETITA DE TIRAMISÙ (SG)",
               "descrizione": "Nuestro postre más antiguo, en carta desde el primer día, servido de una manera muy particular. Muchos lo definen como el mejor tiramisù que han probado. ¡No lo dejes escapar!"},
        "de": {"titolo": "DAS TIRAMISÙ IM BLUMENTOPF (GF)",
               "descrizione": "Unser ältestes Dessert, seit dem ersten Tag auf der Karte, auf ganz besondere Weise serviert. Viele nennen es das beste Tiramisù, das sie je gegessen haben. Lassen Sie es sich nicht entgehen!"},
        "uk": {"titolo": "ТИРАМІСУ В ГОРЩИКУ (БГ)",
               "descrizione": "Наш найдавніший десерт — у меню з першого дня, подається у зовсім особливий спосіб. Багато хто називає його найкращим тирамісу у своєму житті. Не проґавте!"},
    },
    {
        "sezione": "dolci",
        "prezzo": "9",
        "it": {"titolo": "CHEESECAKE AI FRUTTI DI BOSCO (NG)",
               "descrizione": "La nostra versione di una New York Cheesecake in chiave bergamasca, dentro non troverai la Philadelphia ma un mix di formaggi freschi locali. Sopra, a dare gusto, le salse ai frutti di bosco e un coulis al lampone che produciamo noi."},
        "en": {"titolo": "BERRY CHEESECAKE (GF)",
               "descrizione": "Our version of a New York cheesecake with a Bergamo twist: no Philadelphia inside, but a blend of fresh local cheeses. On top, berry sauces and a raspberry coulis we make ourselves."},
        "fr": {"titolo": "CHEESECAKE AUX FRUITS DES BOIS (SG)",
               "descrizione": "Notre version du New York cheesecake revisitée à la bergamasque : à l’intérieur, pas de Philadelphia mais un mélange de fromages frais locaux. Dessus, des sauces aux fruits des bois et un coulis de framboise que nous produisons nous-mêmes."},
        "es": {"titolo": "CHEESECAKE DE FRUTOS ROJOS (SG)",
               "descrizione": "Nuestra versión de la New York cheesecake en clave bergamasca: dentro no encontrarás Philadelphia, sino una mezcla de quesos frescos locales. Encima, salsas de frutos rojos y un coulis de frambuesa que hacemos nosotros."},
        "de": {"titolo": "CHEESECAKE MIT WALDBEEREN (GF)",
               "descrizione": "Unsere Version des New York Cheesecakes auf Bergamasker Art: innen kein Philadelphia, sondern eine Mischung frischer Käse von hier. Darauf Waldbeersaucen und ein Himbeercoulis aus eigener Herstellung."},
        "uk": {"titolo": "ЧИЗКЕЙК ІЗ ЛІСОВИМИ ЯГОДАМИ (БГ)",
               "descrizione": "Наша версія нью-йоркського чизкейка по-бергамськи: усередині не Philadelphia, а суміш місцевих свіжих сирів. Зверху — соуси з лісових ягід і малиновий кулі власного виробництва."},
    },
    {
        "sezione": "dolci",
        "prezzo": "9",
        "it": {"titolo": "TI RICORDI IL “SOLERO”? (NG)(NL)",
               "descrizione": "Semifreddo al cocco, servito su passion fruit, tapioca esplosiva, salsa al cocco ed olio al basilico. Un dolce che ti riporterà agli anni ‘80 con il classico gelato Algida."},
        "en": {"titolo": "REMEMBER THE “SOLERO”? (GF)(LF)",
               "descrizione": "Coconut semifreddo served on passion fruit, popping tapioca, coconut sauce and basil oil. A dessert that will take you straight back to the eighties and the classic Solero ice lolly."},
        "fr": {"titolo": "VOUS VOUS SOUVENEZ DU « SOLERO » ? (SG)(SL)",
               "descrizione": "Semifreddo à la noix de coco servi sur fruit de la passion, tapioca explosif, sauce coco et huile de basilic. Un dessert qui vous ramènera droit aux années 80, au temps du fameux Solero."},
        "es": {"titolo": "¿TE ACUERDAS DEL «SOLERO»? (SG)(SL)",
               "descrizione": "Semifrío de coco sobre fruta de la pasión, tapioca explosiva, salsa de coco y aceite de albahaca. Un postre que te llevará de vuelta a los años 80 y al clásico helado de Frigo."},
        "de": {"titolo": "ERINNERN SIE SICH AN „SOLERO“? (GF)(LF)",
               "descrizione": "Kokos-Semifreddo auf Passionsfrucht, knisternde Tapioka, Kokossauce und Basilikumöl. Ein Dessert, das Sie direkt in die Achtziger zurückbringt – zum klassischen Solero-Eis."},
        "uk": {"titolo": "ПАМ’ЯТАЄТЕ «SOLERO»? (БГ)(БЛ)",
               "descrizione": "Кокосове семіфреддо на маракуї, тапіока, що вибухає в роті, кокосовий соус і базилікова олія. Десерт, який поверне вас просто у вісімдесяті — до культового морозива Algida."},
    },
    {
        "sezione": "dolci",
        "prezzo": "9",
        "it": {"titolo": "PANNA COTTA DELL’INGEGNER DANISI (NG)",
               "descrizione": "La panna cotta è un classico delle Osterie, non poteva mancare tra i nostri dolci! L’abbiamo dedicata ad un nostro caro ospite che ci ha esortato più e più volte a farla, migliorando e perfezionando la ricetta fino alla versione attuale. Quasi perfetta. Sceglila alle AMARENE FABBRI, al CARAMELLO oppure al CIOCCOLATO FUSO."},
        "en": {"titolo": "PANNA COTTA FOR MR DANISI, THE ENGINEER (GF)",
               "descrizione": "Panna cotta is an osteria classic — it could hardly be missing from our list. We have dedicated it to a dear guest who urged us again and again to make it, improving and refining the recipe up to the version you have today. Almost perfect. Choose it with AMARENA FABBRI cherries, with CARAMEL or with MELTED CHOCOLATE."},
        "fr": {"titolo": "LA PANNA COTTA DE L’INGÉNIEUR DANISI (SG)",
               "descrizione": "La panna cotta est un classique des osterie, elle ne pouvait pas manquer ici. Nous l’avons dédiée à un client qui nous est cher et qui nous a poussés encore et encore à la faire, en améliorant et en affinant la recette jusqu’à la version d’aujourd’hui. Presque parfaite. À choisir aux AMARENA FABBRI, au CARAMEL ou au CHOCOLAT FONDU."},
        "es": {"titolo": "LA PANNA COTTA DEL INGENIERO DANISI (SG)",
               "descrizione": "La panna cotta es un clásico de las osterie, ¡no podía faltar entre nuestros postres! Se la dedicamos a un cliente muy querido que nos insistió una y otra vez para que la hiciéramos, mejorando y afinando la receta hasta la versión de hoy. Casi perfecta. Elígela con AMARENA FABBRI, con CARAMELO o con CHOCOLATE FUNDIDO."},
        "de": {"titolo": "DIE PANNA COTTA VON INGENIEUR DANISI (GF)",
               "descrizione": "Panna cotta ist ein Klassiker der Osterien, sie durfte auf unserer Karte nicht fehlen! Wir haben sie einem lieben Gast gewidmet, der uns immer wieder gedrängt hat, sie zu machen; das Rezept wurde dabei so lange verfeinert, bis es bei der heutigen Fassung ankam. Fast perfekt. Zur Wahl mit AMARENA FABBRI, mit KARAMELL oder mit GESCHMOLZENER SCHOKOLADE."},
        "uk": {"titolo": "ПАНАКОТА ВІД ІНЖЕНЕРА ДАНІЗІ (БГ)",
               "descrizione": "Панакота — класика остерій, вона не могла не з’явитися в нашому меню. Ми присвятили її дорогому гостеві, який знову й знову підштовхував нас її зробити, а рецепт удосконалювався до сьогоднішньої версії. Майже досконала. Оберіть її з вишнею AMARENA FABBRI, з карамеллю або з розтопленим шоколадом."},
    },
    {
        "sezione": "dolci",
        "prezzo": "10",
        "it": {"titolo": "PESCA MELBA (NG)",
               "descrizione": "Semifreddo alla vaniglia del Madagascar, pesche cotte in sciroppo, coulis al lampone e una terra di mandorla. L’ultimo dolce inserito in carta, che sta diventando uno dei più scelti!"},
        "en": {"titolo": "PEACH MELBA (GF)",
               "descrizione": "Madagascar vanilla semifreddo, peaches poached in syrup, raspberry coulis and an almond soil. The latest dessert to join the list, and already one of the most ordered!"},
        "fr": {"titolo": "PÊCHE MELBA (SG)",
               "descrizione": "Semifreddo à la vanille de Madagascar, pêches pochées au sirop, coulis de framboise et terre d’amande. Le dernier dessert arrivé à la carte, et déjà l’un des plus commandés !"},
        "es": {"titolo": "MELOCOTÓN MELBA (SG)",
               "descrizione": "Semifrío de vainilla de Madagascar, melocotones en almíbar, coulis de frambuesa y tierra de almendra. El último postre en entrar en carta y ya uno de los más pedidos."},
        "de": {"titolo": "PFIRSICH MELBA (GF)",
               "descrizione": "Semifreddo mit Madagaskar-Vanille, in Sirup pochierte Pfirsiche, Himbeercoulis und krümelige Mandelerde. Das jüngste Dessert auf der Karte – und schon eines der meistbestellten!"},
        "uk": {"titolo": "ПЕРСИК МЕЛЬБА (БГ)",
               "descrizione": "Семіфреддо з мадагаскарською ваніллю, персики в сиропі, малиновий кулі та мигдалева «земля». Найновіший десерт у меню — і вже один із найпопулярніших!"},
    },
]

DEGUSTAZIONI = [
    {
        "prezzo": "60",
        "it": {"nome": "DEGUSTAZIONE",
               "sottotitolo": "“Prima volta”",
               "intro": "Per la prima volta nella nostra osteria ti consigliamo di assaggiare il meglio della cucina Bergamasca nella nostra interpretazione! Il metodo migliore per conoscerci.",
               "note": "Le degustazioni sono da considerarsi per tutto il tavolo. Fatte salve allergie e intolleranze, per le quali proporremo alternative.",
               "steps": ['ANTIPASTO MISTO DELL’OSTERIA', 'CASONCELLI DI MAMMA E PAPÀ', 'CONIGLIO O GUANCETTA a tua scelta', 'DOLCE A SCELTA']},
        "en": {"nome": "TASTING MENU",
               "sottotitolo": "“First time”",
               "intro": "If this is your first time in our osteria, we suggest you taste the best of Bergamasque cooking in our own interpretation. It is the finest way to get to know us.",
               "note": "Tasting menus are intended for the whole table. Allergies and intolerances are the one exception — for those we will gladly suggest an alternative.",
               "steps": ['THE OSTERIA’S MIXED ANTIPASTO', 'MAMMA AND PAPÀ’S CASONCELLI', 'RABBIT OR SUCKLING PIG CHEEK, as you prefer', 'DESSERT OF YOUR CHOICE']},
        "fr": {"nome": "DÉGUSTATION",
               "sottotitolo": "« Première fois »",
               "intro": "Pour votre première fois dans notre osteria, nous vous conseillons de goûter le meilleur de la cuisine bergamasque dans notre interprétation. La plus belle façon de faire connaissance.",
               "note": "Les menus dégustation sont servis pour l’ensemble de la table. Allergies et intolérances exceptées : nous vous proposerons volontiers une alternative.",
               "steps": ['L’ASSORTIMENT D’ANTIPASTI DE L’OSTERIA', 'LES CASONCELLI DE MAMAN ET PAPA', 'LAPIN OU JOUE DE PORCELET, au choix', 'DESSERT AU CHOIX']},
        "es": {"nome": "DEGUSTACIÓN",
               "sottotitolo": "«Primera vez»",
               "intro": "Si es tu primera vez en nuestra osteria, te aconsejamos probar lo mejor de la cocina bergamasca en nuestra interpretación. La mejor manera de conocernos.",
               "note": "Los menús degustación son para toda la mesa. Salvo alergias e intolerancias, para las que propondremos alternativas.",
               "steps": ['ENTRANTE MIXTO DE LA OSTERIA', 'LOS CASONCELLI DE MAMÁ Y PAPÁ', 'CONEJO O CARRILLERA, a tu elección', 'POSTRE A ELEGIR']},
        "de": {"nome": "DEGUSTATIONSMENÜ",
               "sottotitolo": "„Das erste Mal“",
               "intro": "Wenn Sie zum ersten Mal in unserer Osteria sind, empfehlen wir Ihnen das Beste der Bergamasker Küche in unserer Auslegung. Der schönste Weg, uns kennenzulernen.",
               "note": "Die Degustationsmenüs gelten für den ganzen Tisch. Ausgenommen sind Allergien und Unverträglichkeiten – dafür schlagen wir Ihnen gerne Alternativen vor.",
               "steps": ['GEMISCHTE VORSPEISENPLATTE DER OSTERIA', 'CASONCELLI VON MAMMA UND PAPÀ', 'KANINCHEN ODER SPANFERKELBACKE, nach Wahl', 'DESSERT NACH WAHL']},
        "uk": {"nome": "ДЕГУСТАЦІЯ",
               "sottotitolo": "«Перший раз»",
               "intro": "Якщо ви в нашій остерії вперше, радимо скуштувати найкраще з бергамської кухні в нашому прочитанні. Це найліпший спосіб із нами познайомитися.",
               "note": "Дегустаційні меню замовляються на весь стіл. Виняток — алергії та харчова непереносимість: у таких випадках ми запропонуємо альтернативи.",
               "steps": ['АСОРТІ ЗАКУСОК ОСТЕРІЇ', 'CASONCELLI МАМИ Й ТАТА', 'КРОЛИК АБО ЩІЧКА ПОРОСЯТИ, на ваш вибір', 'ДЕСЕРТ НА ВИБІР']},
    },
    {
        "prezzo": "75",
        "it": {"nome": "DEGUSTAZIONE",
               "sottotitolo": "“Fidati dell’oste”",
               "intro": "I piatti consigliati dall’Oste, quelli che rappresentano la stagione ed il momento. Molto spesso con variazioni raccontate a voce.",
               "note": "Le degustazioni sono da considerarsi per tutto il tavolo. Fatte salve allergie e intolleranze, per le quali proporremo alternative.",
               "steps": ['BATTUTA DI MANZO E COCOMERO', 'COZZE IN BLU', 'RISOTTO ALL’ALBICOCCA, AGRÌ DI VALTORTA, MANDORLE E VERMOUTH', 'ANATRA, RIBES E LATTUGA', 'DOLCE A SCELTA']},
        "en": {"nome": "TASTING MENU",
               "sottotitolo": "“Trust the oste”",
               "intro": "The dishes the Oste recommends, the ones that speak of the season and of the moment. Very often with variations told to you at the table.",
               "note": "Tasting menus are intended for the whole table. Allergies and intolerances are the one exception — for those we will gladly suggest an alternative.",
               "steps": ['HAND-CUT BEEF TARTARE AND WATERMELON', 'MUSSELS IN BLUE', 'RISOTTO WITH APRICOT, AGRÌ DI VALTORTA, ALMOND AND VERMOUTH', 'DUCK, REDCURRANT AND LETTUCE', 'DESSERT OF YOUR CHOICE']},
        "fr": {"nome": "DÉGUSTATION",
               "sottotitolo": "« Faites confiance à l’oste »",
               "intro": "Les plats conseillés par l’Oste, ceux qui représentent la saison et le moment. Très souvent avec des variations racontées de vive voix.",
               "note": "Les menus dégustation sont servis pour l’ensemble de la table. Allergies et intolérances exceptées : nous vous proposerons volontiers une alternative.",
               "steps": ['TARTARE DE BŒUF ET PASTÈQUE', 'MOULES EN BLEU', 'RISOTTO À L’ABRICOT, AGRÌ DI VALTORTA, AMANDES ET VERMOUTH', 'CANARD, GROSEILLES ET LAITUE', 'DESSERT AU CHOIX']},
        "es": {"nome": "DEGUSTACIÓN",
               "sottotitolo": "«Fíate del oste»",
               "intro": "Los platos que recomienda el Oste, los que representan la temporada y el momento. Muy a menudo con variaciones contadas de viva voz.",
               "note": "Los menús degustación son para toda la mesa. Salvo alergias e intolerancias, para las que propondremos alternativas.",
               "steps": ['TARTAR DE VACUNO Y SANDÍA', 'MEJILLONES EN AZUL', 'RISOTTO DE ALBARICOQUE, AGRÌ DI VALTORTA, ALMENDRA Y VERMUT', 'PATO, GROSELLA Y LECHUGA', 'POSTRE A ELEGIR']},
        "de": {"nome": "DEGUSTATIONSMENÜ",
               "sottotitolo": "„Vertrauen Sie dem Oste“",
               "intro": "Die Gerichte, die der <i>Oste</i> empfiehlt: jene, die für die Saison und den Moment stehen. Sehr oft mit Abwandlungen, die wir Ihnen am Tisch erzählen.",
               "note": "Die Degustationsmenüs gelten für den ganzen Tisch. Ausgenommen sind Allergien und Unverträglichkeiten – dafür schlagen wir Ihnen gerne Alternativen vor.",
               "steps": ['TATAR VOM RIND UND WASSERMELONE', 'MIESMUSCHELN IN BLAU', 'RISOTTO MIT APRIKOSE, AGRÌ DI VALTORTA, MANDELN UND WERMUT', 'ENTE, JOHANNISBEERE UND KOPFSALAT', 'DESSERT NACH WAHL']},
        "uk": {"nome": "ДЕГУСТАЦІЯ",
               "sottotitolo": "«Довіртеся oste»",
               "intro": "Страви, які радить oste, — ті, що передають сезон і момент. Дуже часто з варіаціями, про які ми розповідаємо за столом.",
               "note": "Дегустаційні меню замовляються на весь стіл. Виняток — алергії та харчова непереносимість: у таких випадках ми запропонуємо альтернативи.",
               "steps": ['ТАРТАР ІЗ ЯЛОВИЧИНИ З КАВУНОМ', 'МІДІЇ В БЛАКИТНОМУ', 'РИЗОТО З АБРИКОСОМ, АГРІ ДІ ВАЛЬТОРТА, МИГДАЛЕМ І ВЕРМУТОМ', 'КАЧКА, ПОРІЧКИ ТА САЛАТ-ЛАТУК', 'ДЕСЕРТ НА ВИБІР']},
    },
]

TESTI = {
    "storia": {
        "it": ['Questa storia comincia molto prima di noi.', 'Comincia con una porta di ferro battuto ben più antica del 1855, l’anno che racconta la nostra fondazione. Un’insegna dipinta con la vecchia dicitura “Antica Trattoria dei Tre Gobbi”, coi tre gobbetti paffuti e sorridenti, appesa in via Broseta da quando nel cortile sostavano diligenze, carri e viaggiatori. Dietro il bancone c’era Michele Bettinelli, oste piccolo e rubicondo, amico d’infanzia del famoso compositore Gaetano Donizetti — che appena poteva tornava fin qui per una polenta come si deve e una serata tra amici veri.', 'Dal 1855 questa insegna non ha mai smesso di accendersi. Sono passate generazioni di osti, due guerre, e Bergamo è cambiata mille volte. I tre gobbi sono sempre qui.', 'Nel settembre del 2017 ho varcato quella porta anch’io; l’anno dopo è toccato a me. Non si “compra” un posto così: se ne diventa custodi. La promessa è semplice: materia prima delle nostre valli, ricette che parlano bergamasco e un posto dove si sta bene senza bisogno di effetti speciali. Sono l’oste e sono il cuoco — ma un’osteria non si guida solo dai fornelli, e quindi mi troverete sempre più spesso anche tra i tavoli, a raccontarvi i piatti. Con me c’è una famiglia intera, dentro e fuori dalla cucina: a partire da mamma Antonella e papà Gerry, che ogni giorno chiudono a mano i nostri casoncelli.'],
        "en": ['This story begins long before us.', 'It begins with a wrought-iron door far older than 1855, the year we give as our founding. With a hand-painted sign bearing the old name “Antica Trattoria dei Tre Gobbi” and its three plump, smiling hunchbacks, hanging in via Broseta since the days when stagecoaches, carts and travellers pulled into the courtyard. Behind the counter stood Michele Bettinelli, a short, ruddy-faced innkeeper and childhood friend of the great composer Gaetano Donizetti — who came back here whenever he could for a proper polenta and an evening among real friends.', 'Since 1855 that sign has never once gone dark. Generations of innkeepers have come and gone, two wars have passed, and Bergamo has changed a thousand times over. The three hunchbacks are still here.', 'In September 2017 I walked through that door myself; a year later it was my turn. You don’t “buy” a place like this: you become its keeper. The promise is a simple one — ingredients from our valleys, recipes that speak Bergamasque, and somewhere you feel at ease with no need for special effects. I am the <i>oste</i> and I am the cook, but an osteria isn’t run from the stove alone, so you will find me more and more often among the tables too, telling you about the dishes. There is a whole family with me, in the kitchen and out of it, starting with mamma Antonella and papà Gerry, who seal our casoncelli by hand every day.'],
        "fr": ['Cette histoire commence bien avant nous.', 'Elle commence par une porte en fer forgé bien plus ancienne que 1855, l’année que l’on donne pour celle de notre fondation. Par une enseigne peinte à la main portant l’ancien nom «\xa0Antica Trattoria dei Tre Gobbi\xa0», avec ses trois bossus dodus et souriants, accrochée via Broseta depuis l’époque où diligences, charrettes et voyageurs faisaient halte dans la cour. Derrière le comptoir se tenait Michele Bettinelli, aubergiste petit et rubicond, ami d’enfance du célèbre compositeur Gaetano Donizetti — qui revenait ici dès qu’il le pouvait pour une polenta comme il faut et une soirée entre vrais amis.', 'Depuis 1855, cette enseigne ne s’est jamais éteinte. Des générations d’aubergistes se sont succédé, deux guerres sont passées, et Bergame a changé mille fois. Les trois bossus, eux, sont toujours là.', 'En septembre 2017, j’ai franchi cette porte moi aussi\xa0; un an plus tard, ce fut mon tour. Un endroit pareil, on ne l’«\xa0achète\xa0» pas\xa0: on en devient le gardien. La promesse est simple — les produits de nos vallées, des recettes qui parlent bergamasque, et un lieu où l’on se sent bien sans avoir besoin d’effets spéciaux. Je suis l’<i>oste</i> et je suis le cuisinier, mais une osteria ne se dirige pas seulement depuis les fourneaux\xa0: vous me trouverez donc de plus en plus souvent en salle aussi, à vous raconter les plats. Avec moi, il y a toute une famille, en cuisine et en dehors, à commencer par maman Antonella et papa Gerry, qui ferment nos casoncelli à la main, chaque jour.'],
        "es": ['Esta historia empieza mucho antes que nosotros.', 'Empieza con una puerta de hierro forjado muy anterior a 1855, el año que damos como el de nuestra fundación. Con un letrero pintado a mano con el viejo nombre «Antica Trattoria dei Tre Gobbi», con los tres jorobaditos rollizos y sonrientes, colgado en la via Broseta desde los tiempos en que el patio acogía diligencias, carros y viajeros. Tras el mostrador estaba Michele Bettinelli, tabernero bajito y rubicundo, amigo de la infancia del célebre compositor Gaetano Donizetti, que en cuanto podía volvía hasta aquí por una polenta como Dios manda y una noche entre amigos de verdad.', 'Desde 1855 este letrero no ha dejado de encenderse ni una sola vez. Han pasado generaciones de taberneros, dos guerras, y Bérgamo ha cambiado mil veces. Los tres jorobados siguen aquí.', 'En septiembre de 2017 crucé yo también aquella puerta; un año después me tocó a mí. Un sitio así no se «compra»: uno se convierte en su guardián. La promesa es sencilla: materia prima de nuestros valles, recetas que hablan bergamasco y un lugar donde se está bien sin necesidad de efectos especiales. Soy el <i>oste</i> y soy el cocinero, pero una osteria no se lleva solo desde los fogones, así que cada vez me encontrarás más a menudo también entre las mesas, contándote los platos. Conmigo hay una familia entera, dentro y fuera de la cocina, empezando por mamá Antonella y papá Gerry, que cada día cierran a mano nuestros casoncelli.'],
        "de": ['Diese Geschichte beginnt lange vor uns.', 'Sie beginnt mit einer schmiedeeisernen Tür, die weit älter ist als 1855 – das Jahr, das wir als unser Gründungsjahr angeben. Mit einem handgemalten Schild, das den alten Namen „Antica Trattoria dei Tre Gobbi“ trägt, mit den drei rundlichen, lächelnden Buckligen – es hängt in der Via Broseta, seit im Hof noch Kutschen, Karren und Reisende Halt machten. Hinter dem Tresen stand Michele Bettinelli, ein kleiner, rotbackiger Wirt und Jugendfreund des berühmten Komponisten Gaetano Donizetti – der, wann immer er konnte, hierher zurückkam, für eine anständige Polenta und einen Abend unter echten Freunden.', 'Seit 1855 hat dieses Schild nie aufgehört zu leuchten. Generationen von Wirten sind gekommen und gegangen, zwei Kriege sind über das Land hinweggezogen, und Bergamo hat sich tausendmal verändert. Die drei Buckligen sind immer noch da.', 'Im September 2017 bin auch ich durch diese Tür getreten; ein Jahr später war ich an der Reihe. Einen solchen Ort „kauft“ man nicht: man wird sein Hüter. Das Versprechen ist einfach – Zutaten aus unseren Tälern, Rezepte, die Bergamaskisch sprechen, und ein Ort, an dem man sich wohlfühlt, ganz ohne Spezialeffekte. Ich bin der <i>Oste</i> und ich bin der Koch, aber eine Osteria führt man nicht allein vom Herd aus, und deshalb werden Sie mich immer öfter auch zwischen den Tischen finden, wo ich Ihnen von den Gerichten erzähle. Mit mir ist eine ganze Familie da, in der Küche und außerhalb: angefangen bei Mamma Antonella und Papà Gerry, die jeden Tag unsere Casoncelli von Hand schließen.'],
        "uk": ['Ця історія почалася задовго до нас.', 'Вона почалася з кованих залізних дверей, значно давніших за 1855 рік — рік, який ми вважаємо роком свого заснування. З мальованої вивіски зі старою назвою «Antica Trattoria dei Tre Gobbi» і трьома пухкенькими усміхненими горбанями, що висить на віа Бросета ще відтоді, коли на подвір’ї спинялися диліжанси, вози й мандрівники. За шинквасом стояв Мікеле Беттінеллі — невисокий рум’яний шинкар, друг дитинства славетного композитора Гаетано Доніцетті, який щоразу, коли міг, повертався сюди по справжню поленту й вечір серед справжніх друзів.', 'Від 1855 року ця вивіска не згасала жодного разу. Змінилися покоління господарів, минули дві війни, Бергамо змінилося тисячу разів. Три горбані досі тут.', 'У вересні 2017 року цей поріг переступив і я; наступного року надійшла моя черга. Таке місце не «купують» — його стають хранителями. Обіцянка проста: продукти з наших долин, рецепти, що говорять бергамською, і місце, де добре без жодних спецефектів. Я — <i>oste</i>, і я ж кухар; але остерією керують не лише від плити, тож дедалі частіше ви бачитимете мене й між столами, де я розповідатиму вам про страви. Зі мною ціла родина, на кухні й поза нею: починаючи від мами Антонелли й тата Джеррі, які щодня зліплюють руками наші casoncelli.'],
    },
    "storia_chiusa": {
        "it": ['Benvenuti.', 'Siete a casa.'],
        "en": ['Welcome.', 'You’re home.'],
        "fr": ['Bienvenue.', 'Vous êtes chez vous.'],
        "es": ['Bienvenido.', 'Aquí estás en casa.'],
        "de": ['Herzlich willkommen.', 'Sie sind hier zu Hause.'],
        "uk": ['Ласкаво просимо.', 'Ви вдома.'],
    },
    "storia_firma": {
        "it": 'Marco, l’oste e cuoco.',
        "en": 'Marco, the oste and the cook.',
        "fr": 'Marco, l’oste et le cuisinier.',
        "es": 'Marco, el oste y cocinero.',
        "de": 'Marco, der Oste und Koch.',
        "uk": 'Марко, oste і кухар.',
    },
    "foto_didascalia": {
        "it": 'L’osteria nel 1907',
        "en": 'The osteria in 1907',
        "fr": 'L’osteria en 1907',
        "es": 'La osteria en 1907',
        "de": 'Die Osteria im Jahr 1907',
        "uk": 'Остерія у 1907 році',
    },
    "allergeni": {
        "it": 'IL NOSTRO PERSONALE È PREPARATO A RISPONDERVI SU ALLERGENI ED INTOLLERANZE.',
        "en": 'OUR STAFF ARE HAPPY TO ANSWER ANY QUESTION ABOUT ALLERGENS AND INTOLERANCES.',
        "fr": 'NOTRE PERSONNEL EST FORMÉ POUR RÉPONDRE À TOUTE QUESTION SUR LES ALLERGÈNES ET LES INTOLÉRANCES.',
        "es": 'NUESTRO PERSONAL ESTÁ PREPARADO PARA RESPONDERTE SOBRE ALÉRGENOS E INTOLERANCIAS.',
        "de": 'UNSER PERSONAL BEANTWORTET IHNEN GERNE ALLE FRAGEN ZU ALLERGENEN UND UNVERTRÄGLICHKEITEN.',
        "uk": 'НАШ ПЕРСОНАЛ ГОТОВИЙ ВІДПОВІСТИ НА ВАШІ ЗАПИТАННЯ ПРО АЛЕРГЕНИ ТА ХАРЧОВУ НЕПЕРЕНОСИМІСТЬ.',
    },
    "bambini_titolo": {
        "it": 'MENÙ BAMBINI',
        "en": 'CHILDREN’S MENU',
        "fr": 'MENU ENFANTS',
        "es": 'MENÚ INFANTIL',
        "de": 'KINDERMENÜ',
        "uk": 'ДИТЯЧЕ МЕНЮ',
    },
    "bambini_sotto": {
        "it": 'DISPONIBILE SU RICHIESTA.',
        "en": 'AVAILABLE ON REQUEST.',
        "fr": 'DISPONIBLE SUR DEMANDE.',
        "es": 'DISPONIBLE BAJO PETICIÓN.',
        "de": 'AUF ANFRAGE ERHÄLTLICH.',
        "uk": 'ЗА ЗАПИТОМ.',
    },
    "bambini_righe": {
        "it": [('PRIMO PIATTO', '10 EURO'), ('SECONDO PIATTO', '15 EURO')],
        "en": [('FIRST COURSE', '10 EUROS'), ('MAIN COURSE', '15 EUROS')],
        "fr": [('PREMIER PLAT', '10 EUROS'), ('PLAT PRINCIPAL', '15 EUROS')],
        "es": [('PRIMER PLATO', '10 EUROS'), ('SEGUNDO PLATO', '15 EUROS')],
        "de": [('ERSTER GANG', '10 EURO'), ('HAUPTGANG', '15 EURO')],
        "uk": [('ПЕРША СТРАВА (ПАСТА АБО РИЗОТО)', '10 ЄВРО'), ('ОСНОВНА СТРАВА', '15 ЄВРО')],
    },
    "bevande": {
        "it": [('TÈ E TISANE', '10', None), ('ESPRESSO', '3', None), ('MOKA “PUMP”', '10', 'DEGUSTAZIONE PER DUE'), ('ACQUA', '3', None), ('COPERTO', '5', None)],
        "en": [('TEA AND HERBAL TEAS', '10', None), ('ESPRESSO', '3', None), ('MOKA “PUMP”', '10', 'TASTING FOR TWO'), ('WATER', '3', None), ('COVER CHARGE', '5', None)],
        "fr": [('THÉS ET TISANES', '10', None), ('ESPRESSO', '3', None), ('MOKA «\xa0PUMP\xa0»', '10', 'DÉGUSTATION POUR DEUX'), ('EAU', '3', None), ('COUVERT', '5', None)],
        "es": [('TÉS E INFUSIONES', '10', None), ('ESPRESSO', '3', None), ('MOKA «PUMP»', '10', 'DEGUSTACIÓN PARA DOS'), ('AGUA', '3', None), ('CUBIERTO', '5', None)],
        "de": [('TEE UND KRÄUTERTEES', '10', None), ('ESPRESSO', '3', None), ('MOKA „PUMP“', '10', 'VERKOSTUNG FÜR ZWEI'), ('WASSER', '3', None), ('GEDECK', '5', None)],
        "uk": [('ЧАЙ І ТРАВ’ЯНІ НАСТОЇ', '10', None), ('ЕСПРЕСО', '3', None), ('МОКА «PUMP»', '10', 'ДЕГУСТАЦІЯ НА ДВОХ'), ('ВОДА', '3', None), ('КУВЕРТ (СЕРВІРУВАННЯ)', '5', None)],
    },
    "dolci_note": {
        "it": ['(NG) NO GLUTINE', '(NL) NO LATTOSIO'],
        "en": ['(GF) GLUTEN FREE', '(LF) LACTOSE FREE'],
        "fr": ['(SG) SANS GLUTEN', '(SL) SANS LACTOSE'],
        "es": ['(SG) SIN GLUTEN', '(SL) SIN LACTOSA'],
        "de": ['(GF) GLUTENFREI', '(LF) LAKTOSEFREI'],
        "uk": ['(БГ) БЕЗ ГЛЮТЕНУ', '(БЛ) БЕЗ ЛАКТОЗИ'],
    },
    "sezioni_titoli": {
        "it": {'antipasti': 'ANTIPASTI', 'paste_risi_zuppe': 'PASTE, RISI E ZUPPE', 'piatti_del_giorno': 'PIATTI DEL GIORNO', 'contorni': 'CONTORNI', 'secondi': 'SECONDI', 'dolci': 'DOLCI', 'degustazioni': 'DEGUSTAZIONE', 'bambini': 'MENÙ BAMBINI'},
        "en": {'antipasti': 'STARTERS', 'paste_risi_zuppe': 'PASTA, RICE AND SOUPS', 'piatti_del_giorno': 'DISHES OF THE DAY', 'contorni': 'SIDES', 'secondi': 'MAIN COURSES', 'dolci': 'DESSERTS', 'degustazioni': 'TASTING MENU', 'bambini': 'CHILDREN’S MENU'},
        "fr": {'antipasti': 'ENTRÉES', 'paste_risi_zuppe': 'PÂTES, RIZ ET SOUPES', 'piatti_del_giorno': 'PLATS DU JOUR', 'contorni': 'ACCOMPAGNEMENTS', 'secondi': 'PLATS', 'dolci': 'DESSERTS', 'degustazioni': 'DÉGUSTATION', 'bambini': 'MENU ENFANTS'},
        "es": {'antipasti': 'ENTRANTES', 'paste_risi_zuppe': 'PASTAS, ARROCES Y SOPAS', 'piatti_del_giorno': 'PLATOS DEL DÍA', 'contorni': 'GUARNICIONES', 'secondi': 'SEGUNDOS', 'dolci': 'POSTRES', 'degustazioni': 'DEGUSTACIÓN', 'bambini': 'MENÚ INFANTIL'},
        "de": {'antipasti': 'VORSPEISEN', 'paste_risi_zuppe': 'PASTA, REIS UND SUPPEN', 'piatti_del_giorno': 'TAGESGERICHTE', 'contorni': 'BEILAGEN', 'secondi': 'HAUPTGERICHTE', 'dolci': 'DESSERTS', 'degustazioni': 'DEGUSTATIONSMENÜ', 'bambini': 'KINDERMENÜ'},
        "uk": {'antipasti': 'ЗАКУСКИ', 'paste_risi_zuppe': 'ПАСТА, РИЗОТО ТА СУПИ', 'piatti_del_giorno': 'СТРАВИ ДНЯ', 'contorni': 'ГАРНІРИ', 'secondi': 'ОСНОВНІ СТРАВИ', 'dolci': 'ДЕСЕРТИ', 'degustazioni': 'ДЕГУСТАЦІЯ', 'bambini': 'ДИТЯЧЕ МЕНЮ'},
    },
}

