# -*- coding: utf-8 -*-
"""Menu Osteria Tre Gobbi — edizione ott/nov/dic 2026.
Traduzioni EN / FR / ES / DE / UK. Piatti rimasti dall'estate: testo revisionato da
madrelingua (ago 2026). Piatti nuovi: DA RIVEDERE prima di approvarli nel tab Traduzioni.

STRUTTURA
  PIATTI       lista di dict, uno per piatto, nell'ordine della carta.
               Chiave di aggancio: it.titolo (titolo italiano esatto).
               Campi: sezione, prezzo, tag (codici IT), varianti (solo formaggi),
               it/en/fr/es/de/uk -> {titolo, descrizione, tag nella lingua}
               descrizione = None dove il piatto non ne ha (voci senza testo).
  DEGUSTAZIONI lista di dict: nome, sottotitolo, intro, note, prezzo, steps.
  TESTI        blocchi non legati a un piatto: storia, etichette di sezione,
               menu bambini, bevande, note allergeni.
  LINGUE       ("it", "en", "fr", "es", "de", "uk") — "it" e' la lingua madre.

NOTE PER IL SEED
  - Il match va fatto su it.titolo normalizzato (trim, casefold, apostrofi
    tipografici uniformati). Le righe non abbinate vanno stampate a video.
  - I tag dietetici NON sono nei titoli: stanno in "tag" (8 codici, legenda in
    TESTI["legenda"]). Sono "adatto a / opzione", non allergeni presenti.
  - Il francese contiene spazi insecabili U+00A0 prima di : ; ! ? e nei « ».
  - <i>...</i> compare in alcuni testi narrativi: e' corsivo, non HTML da fuggire.
"""

LINGUE = ("it", "en", "fr", "es", "de", "uk")

PIATTI = [
    # ── antipasti ─────────────────────────────────────────────────
    {
        "sezione": "antipasti",
        "prezzo": "16",
        "tag": ['V', 'NG', 'OVG'],
        "it": {"titolo": "ROSA DI ZUCCA",
               "descrizione": "Millefoglie di zucca violina e butternut, su crema di zucca hokkaido e fonduta di Taleggio DOP. Adattabile vegana."},
        "en": {"titolo": "PUMPKIN ROSE",
               "descrizione": "A millefeuille of violina and butternut squash on a Hokkaido pumpkin cream with a Taleggio DOP fondue. Can be made vegan.",
               "tag": ['V', 'GF', 'VGO']},
        "fr": {"titolo": "ROSE DE COURGE",
               "descrizione": "Mille-feuille de courge violina et butternut, sur une crème de potimarron hokkaido et une fondue de Taleggio AOP. Peut être préparé en version végane.",
               "tag": ['V', 'SG', 'OVG']},
        "es": {"titolo": "ROSA DE CALABAZA",
               "descrizione": "Milhojas de calabaza violina y butternut, sobre crema de calabaza hokkaido y fondue de Taleggio DOP. Se puede preparar en versión vegana.",
               "tag": ['V', 'SG', 'OVG']},
        "de": {"titolo": "KÜRBISROSE",
               "descrizione": "Millefeuille aus Violina- und Butternutkürbis auf Hokkaido-Kürbiscreme mit Taleggio-DOP-Fondue. Auf Wunsch auch vegan.",
               "tag": ['V', 'GF', 'VGO']},
        "uk": {"titolo": "ГАРБУЗОВА ТРОЯНДА",
               "descrizione": "Мільфей із гарбуза віоліна та батернат на кремі з гарбуза хоккайдо, із фондю з сиру таледжо DOP. Можемо приготувати у веганському варіанті.",
               "tag": ['В', 'БГ', 'ОВГ']},
    },
    {
        "sezione": "antipasti",
        "prezzo": "16",
        "tag": ['NG'],
        "it": {"titolo": "CAPPUCCINO DI BACCALÀ E PATATA",
               "descrizione": "Baccalà mantecato alla veneziana, spuma di patata affumicata e polvere di bottarga."},
        "en": {"titolo": "BACCALÀ AND POTATO “CAPPUCCINO”",
               "descrizione": "Venetian-style whipped salt cod, smoked potato foam and bottarga powder.",
               "tag": ['GF']},
        "fr": {"titolo": "« CAPPUCCINO » DE BACCALÀ ET POMME DE TERRE",
               "descrizione": "Baccalà mantecato à la vénitienne, espuma de pomme de terre fumée et poudre de poutargue.",
               "tag": ['SG']},
        "es": {"titolo": "«CAPUCHINO» DE BACALAO Y PATATA",
               "descrizione": "Bacalao mantecado a la veneciana, espuma de patata ahumada y polvo de botarga.",
               "tag": ['SG']},
        "de": {"titolo": "„CAPPUCCINO“ VON BACCALÀ UND KARTOFFEL",
               "descrizione": "Baccalà mantecato nach venezianischer Art, Schaum von geräucherter Kartoffel und Bottarga-Pulver.",
               "tag": ['GF']},
        "uk": {"titolo": "«КАПУЧИНО» З BACCALÀ ТА КАРТОПЛІ",
               "descrizione": "Baccalà mantecato по-венеційськи, піна з копченої картоплі та порошок із ботарги.",
               "tag": ['БГ']},
    },
    {
        "sezione": "antipasti",
        "prezzo": "16",
        "tag": ['NG'],
        "it": {"titolo": "COZZE IN BLU",
               "descrizione": "Cozze appena scottate al forno, fonduta leggera di Strachitunt, limone sotto sale ed olio al prezzemolo."},
        "en": {"titolo": "MUSSELS IN BLUE",
               "descrizione": "Mussels flashed in the oven, a light Strachitunt fondue, preserved lemon and parsley oil.",
               "tag": ['GF']},
        "fr": {"titolo": "MOULES EN BLEU",
               "descrizione": "Moules à peine saisies au four, fondue légère de Strachitunt, citron confit au sel et huile de persil.",
               "tag": ['SG']},
        "es": {"titolo": "MEJILLONES EN AZUL",
               "descrizione": "Mejillones apenas pasados por el horno, fondue ligera de Strachitunt, limón en salazón y aceite de perejil.",
               "tag": ['SG']},
        "de": {"titolo": "MIESMUSCHELN IN BLAU",
               "descrizione": "Kurz im Ofen überbackene Miesmuscheln, leichtes Fondue vom Strachitunt, Salzzitrone und Petersilienöl.",
               "tag": ['GF']},
        "uk": {"titolo": "МІДІЇ В БЛАКИТНОМУ",
               "descrizione": "Мідії, ледь припечені в духовці, легке фондю зі стракітунта, лимон у солі та олія з петрушки.",
               "tag": ['БГ']},
    },
    {
        "sezione": "antipasti",
        "prezzo": "16",
        "tag": ['NG'],
        "it": {"titolo": "SUA MAESTÀ “LA TARAGNA”",
               "descrizione": "Polenta cotta lentamente con burro, salvia e cinque formaggi bergamaschi: taleggio, stracchino, formai de mut, branzi e formagella."},
        "en": {"titolo": "HER MAJESTY “LA TARAGNA”",
               "descrizione": "Polenta cooked slowly with butter, sage and five Bergamasque cheeses: Taleggio, Stracchino, Formai de Mut, Branzi and Formagella.",
               "tag": ['GF']},
        "fr": {"titolo": "SA MAJESTÉ « LA TARAGNA »",
               "descrizione": "Polenta longuement cuite au beurre et à la sauge avec cinq fromages bergamasques : Taleggio, Stracchino, Formai de Mut, Branzi et Formagella.",
               "tag": ['SG']},
        "es": {"titolo": "SU MAJESTAD «LA TARAGNA»",
               "descrizione": "Polenta cocida despacio con mantequilla, salvia y cinco quesos bergamascos: Taleggio, Stracchino, Formai de Mut, Branzi y Formagella.",
               "tag": ['SG']},
        "de": {"titolo": "IHRE MAJESTÄT „LA TARAGNA“",
               "descrizione": "Langsam gekochte Polenta mit Butter, Salbei und fünf Bergamasker Käsesorten: Taleggio, Stracchino, Formai de Mut, Branzi und Formagella.",
               "tag": ['GF']},
        "uk": {"titolo": "ЇЇ ВЕЛИЧНІСТЬ «ЛА ТАРАНЬЯ»",
               "descrizione": "Полента, повільно зварена на вершковому маслі з шавлією та п’ятьма бергамськими сирами: таледжо, стракіно, формай де мут, брандзі й формаджелла.",
               "tag": ['БГ']},
    },
    {
        "sezione": "antipasti",
        "prezzo": "22",
        "tag": ['NG'],
        "it": {"titolo": "BATTUTA DI MANZO, PORCINI E NOCCIOLA",
               "descrizione": "Battuta di manzo al coltello condita alla moda dell’osteria, porcini spadellati, nocciole tostate con un filo d’olio di nocciola e un tuorlo al centro che lega tutto."},
        "en": {"titolo": "HAND-CUT BEEF TARTARE, PORCINI AND HAZELNUT",
               "descrizione": "Beef cut by hand and seasoned the osteria way, pan-tossed porcini, toasted hazelnuts with a drizzle of hazelnut oil, and an egg yolk in the centre that brings it all together.",
               "tag": ['GF']},
        "fr": {"titolo": "TARTARE DE BŒUF, CÈPES ET NOISETTE",
               "descrizione": "Bœuf coupé au couteau et assaisonné à la façon de l’osteria, cèpes poêlés, noisettes torréfiées avec un filet d’huile de noisette, et un jaune d’œuf au centre qui lie le tout.",
               "tag": ['SG']},
        "es": {"titolo": "TARTAR DE VACUNO, BOLETUS Y AVELLANA",
               "descrizione": "Vacuno picado a cuchillo y aliñado al estilo de la osteria, boletus salteados, avellanas tostadas con un hilo de aceite de avellana y una yema en el centro que lo une todo.",
               "tag": ['SG']},
        "de": {"titolo": "TATAR VOM RIND, STEINPILZE UND HASELNUSS",
               "descrizione": "Mit dem Messer geschnittenes Rindfleisch, nach Art der Osteria angemacht, gebratene Steinpilze, geröstete Haselnüsse mit einem Schuss Haselnussöl und in der Mitte ein Eigelb, das alles verbindet.",
               "tag": ['GF']},
        "uk": {"titolo": "ТАРТАР ІЗ ЯЛОВИЧИНИ, БІЛІ ГРИБИ ТА ФУНДУК",
               "descrizione": "Яловичина, нарізана ножем і заправлена по-нашому, обсмажені білі гриби, підсмажений фундук із краплею горіхової олії та жовток у центрі, що поєднує все разом.",
               "tag": ['БГ']},
    },
    {
        "sezione": "antipasti",
        "prezzo": "22",
        "tag": ['NG'],
        "it": {"titolo": "IL VITELLO TONNATO DELL’OSTERIA",
               "descrizione": "Spuma di salsa tonnata fresca, fondo bruno e capperi su un meraviglioso girello di vitello cotto al punto rosa. Ispirato da Diego Rossi, e a lui dedicato."},
        "en": {"titolo": "THE OSTERIA’S VITELLO TONNATO",
               "descrizione": "Fresh tuna-sauce foam, brown jus and capers over a beautiful eye round of veal cooked blushing pink. Inspired by Diego Rossi, and dedicated to him.",
               "tag": ['GF']},
        "fr": {"titolo": "LE VITELLO TONNATO DE L’OSTERIA",
               "descrizione": "Espuma de sauce au thon toute fraîche, fond brun et câpres sur un magnifique rond de gîte de veau cuit rosé. Inspiré par Diego Rossi, et qui lui est dédié.",
               "tag": ['SG']},
        "es": {"titolo": "EL VITELLO TONNATO DE LA OSTERIA",
               "descrizione": "Espuma de salsa de atún recién hecha, fondo oscuro y alcaparras sobre un espléndido redondo de ternera cocinado al punto rosa. Inspirado en Diego Rossi, y dedicado a él.",
               "tag": ['SG']},
        "de": {"titolo": "UNSER VITELLO TONNATO",
               "descrizione": "Schaum von frischer Thunfischsauce, brauner Jus und Kapern auf einer wunderbaren, rosa gegarten Kalbsrolle. Inspiriert von Diego Rossi und ihm gewidmet.",
               "tag": ['GF']},
        "uk": {"titolo": "VITELLO TONNATO НАШОЇ ОСТЕРІЇ",
               "descrizione": "Піна зі свіжого тунцевого соусу, темний м’ясний соус і каперси на чудовому шматку телячого огузка, приготованому до рожевого. Натхнення — Дієго Россі, йому ж і присвячено.",
               "tag": ['БГ']},
    },
    {
        "sezione": "antipasti",
        "prezzo": "16",
        "tag": [],
        "it": {"titolo": "IL SALAME DEL ROBERTO CON LA GIARDINIERA",
               "descrizione": "Il salame che fa il Roberto, stagionato lentamente in cantina e tagliato a fette grosse, accompagnato dalle nostre verdure."},
        "en": {"titolo": "ROBERTO’S SALAME WITH GIARDINIERA",
               "descrizione": "The salame Roberto makes, aged slowly down in the cellar and cut into thick slices, with our own pickled vegetables.",
               "tag": []},
        "fr": {"titolo": "LE SALAME DE ROBERTO ET SA GIARDINIERA",
               "descrizione": "Le salame que fait Roberto, affiné lentement en cave et coupé en tranches épaisses, accompagné de nos légumes au vinaigre.",
               "tag": []},
        "es": {"titolo": "EL SALAMI DE ROBERTO CON GIARDINIERA",
               "descrizione": "El salami que hace Roberto, curado despacio en la bodega y cortado en lonchas gruesas, con nuestras verduras en vinagre.",
               "tag": []},
        "de": {"titolo": "ROBERTOS SALAMI MIT GIARDINIERA",
               "descrizione": "Die Salami von Roberto: langsam im Keller gereift, in dicke Scheiben geschnitten, dazu unser eingelegtes Gemüse.",
               "tag": []},
        "uk": {"titolo": "САЛЯМІ ВІД РОБЕРТО З ДЖАРДІНЬЄРОЮ",
               "descrizione": "Салямі, яку робить Роберто: повільно визріває в підвалі, нарізана товстими кружальцями, з нашими маринованими овочами.",
               "tag": []},
    },
    {
        "sezione": "antipasti",
        "prezzo": "20",
        "tag": ['NG'],
        "it": {"titolo": "I SALUMI MISTI DELL’OSTERIA",
               "descrizione": None},
        "en": {"titolo": "THE OSTERIA’S MIXED SALUMI",
               "descrizione": None,
               "tag": ['GF']},
        "fr": {"titolo": "L’ASSIETTE DE SALUMI DE L’OSTERIA",
               "descrizione": None,
               "tag": ['SG']},
        "es": {"titolo": "SURTIDO DE SALUMI DE LA OSTERIA",
               "descrizione": None,
               "tag": ['SG']},
        "de": {"titolo": "UNSERE SALUMI-AUSWAHL",
               "descrizione": None,
               "tag": ['GF']},
        "uk": {"titolo": "НАШЕ АСОРТІ SALUMI",
               "descrizione": None,
               "tag": ['БГ']},
    },
    {
        "sezione": "antipasti",
        "prezzo": None,
        "tag": ['NG'],
        "varianti": [('ITALIANI (pezzi 4/6)', '14/20'), ('FRANCESI (pezzi 3/5)', '15/25')],
        "it": {"titolo": "LE SELEZIONI DI FORMAGGI",
               "descrizione": None},
        "en": {"titolo": "OUR CHEESE SELECTIONS",
               "descrizione": None,
               "varianti": [('ITALIAN (4/6 pieces)', '14/20'), ('FRENCH (3/5 pieces)', '15/25')],
               "tag": ['GF']},
        "fr": {"titolo": "NOS SÉLECTIONS DE FROMAGES",
               "descrizione": None,
               "varianti": [('ITALIENS (4/6 morceaux)', '14/20'), ('FRANÇAIS (3/5 morceaux)', '15/25')],
               "tag": ['SG']},
        "es": {"titolo": "NUESTRAS SELECCIONES DE QUESOS",
               "descrizione": None,
               "varianti": [('ITALIANOS (4/6 piezas)', '14/20'), ('FRANCESES (3/5 piezas)', '15/25')],
               "tag": ['SG']},
        "de": {"titolo": "UNSERE KÄSEAUSWAHL",
               "descrizione": None,
               "varianti": [('ITALIENISCH (4/6 Stück)', '14/20'), ('FRANZÖSISCH (3/5 Stück)', '15/25')],
               "tag": ['GF']},
        "uk": {"titolo": "НАШІ ДОБІРКИ СИРІВ",
               "descrizione": None,
               "varianti": [('ІТАЛІЙСЬКІ (4/6 шматочків)', '14/20'), ('ФРАНЦУЗЬКІ (3/5 шматочків)', '15/25')],
               "tag": ['БГ']},
    },
    # ── paste_risi_zuppe ──────────────────────────────────────────
    {
        "sezione": "paste_risi_zuppe",
        "prezzo": "18",
        "tag": ['NG', 'V', 'OVG'],
        "it": {"titolo": "RISOTTO ALLO STRACCHINO ALL’ANTICA, MELA KISSABEL E SIDRO",
               "descrizione": "Carnaroli riserva “San Massimo” sfumato al sidro, mantecato allo Stracchino all’antica delle valli orobiche, Presidio Slow Food, con la mela dalla polpa rossa come una ciliegia."},
        "en": {"titolo": "RISOTTO WITH STRACCHINO ALL’ANTICA, KISSABEL APPLE AND CIDER",
               "descrizione": "Carnaroli “San Massimo” Riserva rice deglazed with cider, stirred through with Stracchino all’antica from the Orobic valleys — a Slow Food Presidium cheese — with the apple whose flesh is as red as a cherry.",
               "tag": ['GF', 'V', 'VGO']},
        "fr": {"titolo": "RISOTTO AU STRACCHINO ALL’ANTICA, POMME KISSABEL ET CIDRE",
               "descrizione": "Riz Carnaroli riserva « San Massimo » déglacé au cidre, lié au Stracchino all’antica des vallées orobiennes — sentinelle Slow Food — avec la pomme à la chair rouge comme une cerise.",
               "tag": ['SG', 'V', 'OVG']},
        "es": {"titolo": "RISOTTO DE STRACCHINO ALL’ANTICA, MANZANA KISSABEL Y SIDRA",
               "descrizione": "Carnaroli riserva «San Massimo» regado con sidra, mantecado con Stracchino all’antica de los valles orobicos —Baluarte Slow Food— y con la manzana de pulpa roja como una cereza.",
               "tag": ['SG', 'V', 'OVG']},
        "de": {"titolo": "RISOTTO MIT STRACCHINO ALL’ANTICA, KISSABEL-APFEL UND CIDRE",
               "descrizione": "Carnaroli riserva „San Massimo“, mit Cidre abgelöscht, mit Stracchino all’antica aus den Bergamasker Alpentälern – einem Slow-Food-Presidio-Käse – montiert, dazu der Apfel mit kirschrotem Fruchtfleisch.",
               "tag": ['GF', 'V', 'VGO']},
        "uk": {"titolo": "РИЗОТО ЗІ СТРАККІНО ALL’ANTICA, ЯБЛУКОМ KISSABEL І СИДРОМ",
               "descrizione": "Карнаролі riserva «San Massimo», збризнутий сидром, вимішаний зі страккіно all’antica з Оробських долин (Presidio Slow Food), з яблуком, м’якоть якого червона, як вишня.",
               "tag": ['БГ', 'В', 'ОВГ']},
    },
    {
        "sezione": "paste_risi_zuppe",
        "prezzo": "18",
        "tag": ['V'],
        "it": {"titolo": "FETTUCCINE ALL’ALFREDO SE FOSSE NATO A BERGAMO",
               "descrizione": "Pasta fresca mantecata al burro e formai de mut DOP: se le provi, non le dimentichi."},
        "en": {"titolo": "FETTUCCINE ALL’ALFREDO, HAD ALFREDO BEEN BORN IN BERGAMO",
               "descrizione": "Fresh pasta stirred through butter and Formai de Mut DOP: taste them once and you won’t forget them.",
               "tag": ['V']},
        "fr": {"titolo": "FETTUCCINE ALL’ALFREDO, SI ALFREDO ÉTAIT NÉ À BERGAME",
               "descrizione": "Pâtes fraîches montées au beurre et au formai de mut DOP : si vous les goûtez, vous ne les oublierez pas.",
               "tag": ['V']},
        "es": {"titolo": "FETTUCCINE ALL’ALFREDO SI ALFREDO HUBIERA NACIDO EN BÉRGAMO",
               "descrizione": "Pasta fresca mantecada con mantequilla y formai de mut DOP: si las pruebas, no las olvidas.",
               "tag": ['V']},
        "de": {"titolo": "FETTUCCINE ALL’ALFREDO, WÄRE ALFREDO IN BERGAMO GEBOREN",
               "descrizione": "Frische Pasta mit Butter und Formai de Mut DOP montiert: einmal probiert, nie wieder vergessen.",
               "tag": ['V']},
        "uk": {"titolo": "FETTUCCINE ALL’ALFREDO, ЯКБИ АЛЬФРЕДО НАРОДИВСЯ В БЕРГАМО",
               "descrizione": "Свіжа паста, вимішана з вершковим маслом і сиром формай де мут DOP: спробуєте — не забудете.",
               "tag": ['В']},
    },
    {
        "sezione": "paste_risi_zuppe",
        "prezzo": "18",
        "tag": ['ONL'],
        "it": {"titolo": "CASONCELLI DI MAMMA E PAPÀ",
               "descrizione": "Sono proprio i genitori del nostro oste Marco: Antonella e Gerry che ogni giorno ci preparano questa leccornia con la ricetta della nostra famiglia."},
        "en": {"titolo": "MAMMA AND PAPÀ’S CASONCELLI",
               "descrizione": "Bergamo’s own filled pasta. They really are the parents of our oste Marco: Antonella and Gerry, who make us this delicacy every day with our family recipe.",
               "tag": ['LFO']},
        "fr": {"titolo": "LES CASONCELLI DE MAMAN ET PAPA",
               "descrizione": "Les raviolis de Bergame. Ce sont vraiment les parents de notre oste Marco : Antonella et Gerry, qui nous préparent chaque jour cette gourmandise avec la recette de la famille.",
               "tag": ['OSL']},
        "es": {"titolo": "LOS CASONCELLI DE MAMÁ Y PAPÁ",
               "descrizione": "La pasta rellena de Bérgamo. Son de verdad los padres de nuestro oste Marco: Antonella y Gerry, que cada día nos preparan esta delicia con la receta de la familia.",
               "tag": ['OSL']},
        "de": {"titolo": "CASONCELLI VON MAMMA UND PAPÀ",
               "descrizione": "Die gefüllte Pasta Bergamos. Es sind wirklich die Eltern unseres <i>Oste</i> Marco: Antonella und Gerry, die uns diese Köstlichkeit jeden Tag nach dem Familienrezept zubereiten.",
               "tag": ['LFO']},
        "uk": {"titolo": "CASONCELLI МАМИ Й ТАТА",
               "descrizione": "Фарширована паста, гордість Бергамо. Це справді батьки нашого oste Марка: Антонелла і Джеррі, які щодня готують нам цю смакоту за родинним рецептом.",
               "tag": ['ОБЛ']},
    },
    {
        "sezione": "paste_risi_zuppe",
        "prezzo": "20",
        "tag": ['ONG', 'ONL'],
        "it": {"titolo": "FUSILLONI AL SALMÌ DI LEPRE E BRANZI",
               "descrizione": "Fusillone Mancini condito con un sugo di lepre cotto lentamente con Valcalepio, ginepro, cannella ed anice stellato. Il tutto finito con una grattugiata generosa di Branzi giovane a mantecare."},
        "en": {"titolo": "FUSILLONI WITH HARE SALMÌ AND BRANZI",
               "descrizione": "Mancini fusillone in a hare sauce cooked slowly with Valcalepio wine, juniper, cinnamon and star anise, all finished with a generous grating of young Branzi.",
               "tag": ['GFO', 'LFO']},
        "fr": {"titolo": "FUSILLONI AU SALMIS DE LIÈVRE ET BRANZI",
               "descrizione": "Fusillone Mancini dans une sauce au lièvre longuement mijotée au Valcalepio, genièvre, cannelle et anis étoilé, le tout lié d’une généreuse râpée de Branzi jeune.",
               "tag": ['OSG', 'OSL']},
        "es": {"titolo": "FUSILLONI EN SALMÍ DE LIEBRE Y BRANZI",
               "descrizione": "Fusillone Mancini con una salsa de liebre cocida despacio con Valcalepio, enebro, canela y anís estrellado, todo mantecado con una ralladura generosa de Branzi joven.",
               "tag": ['OSG', 'OSL']},
        "de": {"titolo": "FUSILLONI MIT HASEN-SALMÌ UND BRANZI",
               "descrizione": "Fusillone aus dem Pastificio Mancini in einer Hasensauce, langsam geschmort mit Valcalepio-Rotwein, Wacholder, Zimt und Sternanis, zum Schluss großzügig mit jungem Branzi überrieben.",
               "tag": ['GFO', 'LFO']},
        "uk": {"titolo": "FUSILLONI З САЛЬМІ ІЗ ЗАЙЦЯ ТА СИРОМ БРАНДЗІ",
               "descrizione": "Fusillone від Mancini із соусом із зайця, повільно тушкованим із вином Валькалепіо, ялівцем, корицею та бадьяном, і завершений щедрою стружкою молодого брандзі.",
               "tag": ['ОБГ', 'ОБЛ']},
    },
    {
        "sezione": "paste_risi_zuppe",
        "prezzo": "16",
        "tag": ['VG', 'ONG'],
        "it": {"titolo": "PASTA MISTA E FAGIOLI GIALÈT",
               "descrizione": "La “pasta dei frati” di casa nostra: i fondi delle confezioni mischiati insieme, cotti con i fagioli gialèt della Val Belluna, Presidio Slow Food, castagne arrostite e olio al rosmarino."},
        "en": {"titolo": "PASTA MISTA AND GIALÈT BEANS",
               "descrizione": "Our own “friars’ pasta”: the odds and ends from the bottom of the packets, mixed together and cooked with gialèt beans from Val Belluna — a Slow Food Presidium — roast chestnuts and rosemary oil.",
               "tag": ['VG', 'GFO']},
        "fr": {"titolo": "PASTA MISTA ET HARICOTS GIALÈT",
               "descrizione": "La « pâte des moines » de la maison : les fonds de paquets mélangés, cuits avec les haricots gialèt du Val Belluna — sentinelle Slow Food —, des châtaignes rôties et une huile au romarin.",
               "tag": ['VG', 'OSG']},
        "es": {"titolo": "PASTA MISTA Y ALUBIAS GIALÈT",
               "descrizione": "La «pasta de los frailes» de nuestra casa: los restos del fondo de los paquetes mezclados, cocidos con alubias gialèt del Val Belluna —Baluarte Slow Food—, castañas asadas y aceite de romero.",
               "tag": ['VG', 'OSG']},
        "de": {"titolo": "PASTA MISTA MIT GIALÈT-BOHNEN",
               "descrizione": "Die „Mönchspasta“ unseres Hauses: die Reste vom Boden der Packungen, gemischt und gekocht mit Gialèt-Bohnen aus dem Val Belluna (Slow-Food-Presidio), gerösteten Maronen und Rosmarinöl.",
               "tag": ['VG', 'GFO']},
        "uk": {"titolo": "ПАСТА МІСТА З КВАСОЛЕЮ ДЖАЛЕТ",
               "descrizione": "Наша домашня «паста ченців»: залишки з дна пачок, змішані разом і зварені з квасолею джалет із Валь-Беллуна (Presidio Slow Food), печеними каштанами та розмариновою олією.",
               "tag": ['ВГ', 'ОБГ']},
    },
    {
        "sezione": "paste_risi_zuppe",
        "prezzo": "22",
        "tag": ['ONG'],
        "it": {"titolo": "PIPE RIGATE, BISQUE DI GAMBERI E RISTRETTO DI MOSCATO DI SCANZO",
               "descrizione": "Bisque concentrata fatta in casa con le teste e i carapaci dei gamberi, e un ristretto di Moscato di Scanzo DOCG, il passito rosso dei colli di Bergamo."},
        "en": {"titolo": "PIPE RIGATE, PRAWN BISQUE AND MOSCATO DI SCANZO REDUCTION",
               "descrizione": "A concentrated bisque made in-house from prawn heads and shells, with a reduction of Moscato di Scanzo DOCG, the red passito wine from the hills of Bergamo.",
               "tag": ['GFO']},
        "fr": {"titolo": "PIPE RIGATE, BISQUE DE CREVETTES ET RÉDUCTION DE MOSCATO DI SCANZO",
               "descrizione": "Bisque concentrée maison, préparée avec les têtes et les carapaces des crevettes, et une réduction de Moscato di Scanzo DOCG, le vin passito rouge des collines de Bergame.",
               "tag": ['OSG']},
        "es": {"titolo": "PIPE RIGATE, BISQUE DE GAMBAS Y REDUCCIÓN DE MOSCATO DI SCANZO",
               "descrizione": "Bisque concentrada hecha en casa con las cabezas y los caparazones de las gambas, y una reducción de Moscato di Scanzo DOCG, el vino passito tinto de las colinas de Bérgamo.",
               "tag": ['OSG']},
        "de": {"titolo": "PIPE RIGATE, GARNELENBISQUE UND MOSCATO-DI-SCANZO-REDUKTION",
               "descrizione": "Hausgemachte, konzentrierte Bisque aus Garnelenköpfen und -schalen, dazu eine Reduktion aus Moscato di Scanzo DOCG, dem roten Passito von den Hügeln Bergamos.",
               "tag": ['GFO']},
        "uk": {"titolo": "ПІПЕ РІГАТЕ, БІСК ІЗ КРЕВЕТОК І РЕДУКЦІЯ МОСКАТО ДІ СКАНЦО",
               "descrizione": "Концентрований біск власного приготування з голів і панцирів креветок та редукція Moscato di Scanzo DOCG — червоного вина пасіто з пагорбів Бергамо.",
               "tag": ['ОБГ']},
    },
    {
        "sezione": "paste_risi_zuppe",
        "prezzo": "20",
        "tag": [],
        "it": {"titolo": "LASAGNETTA AL RAGÙ BIANCO DEI TRE GOBBI",
               "descrizione": "Una cottura di tre giorni per un ragù con le carni bianche di faraona, gallina, pollo, anatra e coniglio. Succulento, generoso, buono. Chiuso in una golosissima lasagna."},
        "en": {"titolo": "THE TRE GOBBI’S LITTLE LASAGNA WITH WHITE RAGÙ",
               "descrizione": "Three days of cooking for a ragù of white meats: guinea fowl, hen, chicken, duck and rabbit. Succulent, generous, good. Sealed inside a thoroughly indulgent lasagna.",
               "tag": []},
        "fr": {"titolo": "PETITE LASAGNE AU RAGÙ BLANC DES TRE GOBBI",
               "descrizione": "Trois jours de cuisson pour un ragù de viandes blanches : pintade, poule, poulet, canard et lapin. Succulent, généreux, bon. Enfermé dans une lasagne des plus gourmandes.",
               "tag": []},
        "es": {"titolo": "LASAÑITA DE RAGÙ BLANCO DE LOS TRE GOBBI",
               "descrizione": "Tres días de cocción para un ragù de carnes blancas: pintada, gallina, pollo, pato y conejo. Jugoso, generoso, bueno. Encerrado en una lasaña de lo más golosa.",
               "tag": []},
        "de": {"titolo": "KLEINE LASAGNE MIT WEISSEM RAGÙ DER TRE GOBBI",
               "descrizione": "Drei Tage Garzeit für ein Ragù aus hellem Fleisch: Perlhuhn, Suppenhuhn, Hähnchen, Ente und Kaninchen. Saftig, großzügig, gut. Eingeschlossen in eine verführerische Lasagne.",
               "tag": []},
        "uk": {"titolo": "ЛАЗАНЬЄТТА З БІЛИМ РАГУ ВІД TRE GOBBI",
               "descrizione": "Три дні готування для рагу з білого м’яса: цесарки, курки, курчати, качки та кролика. Соковите, щедре, смачне. Загорнуте в неймовірно спокусливу лазанью.",
               "tag": []},
    },
    # ── piatti_del_giorno ─────────────────────────────────────────
    {
        "sezione": "piatti_del_giorno",
        "prezzo": "da 14 a 26",
        "tag": [],
        "it": {"titolo": "RACCONTATI A VOCE",
               "descrizione": "Come sulla lavagna dell’osteria, tutte le idee del giorno con i prodotti migliori in tiratura limitata. Possono finire subito!"},
        "en": {"titolo": "TOLD TO YOU AT THE TABLE",
               "descrizione": "Just like the osteria’s chalkboard: all of today’s ideas with the best produce, in very limited quantities. They can go in minutes!",
               "tag": []},
        "fr": {"titolo": "RACONTÉS DE VIVE VOIX",
               "descrizione": "Comme sur l’ardoise de l’osteria, toutes les idées du jour avec les meilleurs produits, en quantité limitée. Elles peuvent partir très vite !",
               "tag": []},
        "es": {"titolo": "CONTADOS DE VIVA VOZ",
               "descrizione": "Como en la pizarra de la osteria, todas las ideas del día con los mejores productos, en cantidad limitada. ¡Se pueden acabar enseguida!",
               "tag": []},
        "de": {"titolo": "MÜNDLICH ERZÄHLT",
               "descrizione": "Wie auf der Tafel der Osteria: alle Ideen des Tages mit den besten Produkten, in kleiner Menge zubereitet. Diese Gerichte sind oft schnell vergriffen!",
               "tag": []},
        "uk": {"titolo": "РОЗКАЖЕМО ВАМ ОСОБИСТО",
               "descrizione": "Як на грифельній дошці остерії — усі ідеї дня з найкращих продуктів, у лімітованій кількості. Можуть закінчитися миттю!",
               "tag": []},
    },
    # ── secondi ───────────────────────────────────────────────────
    {
        "sezione": "secondi",
        "prezzo": "26",
        "tag": ['NG', 'ONL'],
        "it": {"titolo": "ANATRA, BARBABIETOLA, ROSA CANINA E CAFFÈ",
               "descrizione": "Petto d’anatra in lunga cottura, fondo al caffè della nostra moka, crema di barbabietola e agrodolce di bacche di rosa canina dei nostri colli."},
        "en": {"titolo": "DUCK, BEETROOT, ROSEHIP AND COFFEE",
               "descrizione": "Slow-cooked duck breast, a jus made with coffee from our moka, beetroot cream and a sweet-and-sour of rosehips from our hills.",
               "tag": ['GF', 'LFO']},
        "fr": {"titolo": "CANARD, BETTERAVE, ÉGLANTIER ET CAFÉ",
               "descrizione": "Magret de canard en cuisson lente, jus au café de notre moka, crème de betterave et aigre-doux de baies d’églantier de nos collines.",
               "tag": ['SG', 'OSL']},
        "es": {"titolo": "PATO, REMOLACHA, ESCARAMUJO Y CAFÉ",
               "descrizione": "Pechuga de pato en cocción lenta, fondo al café de nuestra moka, crema de remolacha y agridulce de escaramujo de nuestras colinas.",
               "tag": ['SG', 'OSL']},
        "de": {"titolo": "ENTE, ROTE BETE, HAGEBUTTE UND KAFFEE",
               "descrizione": "Langsam gegarte Entenbrust, Jus mit Kaffee aus unserer Moka, Rote-Bete-Creme und süß-sauer eingelegte Hagebutten von unseren Hügeln.",
               "tag": ['GF', 'LFO']},
        "uk": {"titolo": "КАЧКА, БУРЯК, ШИПШИНА ТА КАВА",
               "descrizione": "Качина грудка тривалого готування, соус на каві з нашої мока, крем із буряка та кисло-солодкі ягоди шипшини з наших пагорбів.",
               "tag": ['БГ', 'ОБЛ']},
    },
    {
        "sezione": "secondi",
        "prezzo": "35",
        "tag": ['NG', 'ONL'],
        "it": {"titolo": "FILETTO ALLA DONIZETTI",
               "descrizione": "Filetto di manzo, il suo fondo di cottura, crema di topinambur, pera cotta nel Valcalepio, lardo che si scioglie sul filetto e tartufo nero grattato."},
        "en": {"titolo": "BEEF FILLET ALLA DONIZETTI",
               "descrizione": "Beef fillet with its own cooking juices, Jerusalem artichoke cream, pear poached in Valcalepio wine, lardo melting over the fillet and grated black truffle.",
               "tag": ['GF', 'LFO']},
        "fr": {"titolo": "FILET DE BŒUF À LA DONIZETTI",
               "descrizione": "Filet de bœuf, son jus de cuisson, crème de topinambour, poire pochée au Valcalepio, lard qui fond sur le filet et truffe noire râpée.",
               "tag": ['SG', 'OSL']},
        "es": {"titolo": "SOLOMILLO A LA DONIZETTI",
               "descrizione": "Solomillo de vacuno, su jugo de cocción, crema de tupinambo, pera cocida en Valcalepio, lardo que se funde sobre el solomillo y trufa negra rallada.",
               "tag": ['SG', 'OSL']},
        "de": {"titolo": "RINDERFILET NACH DONIZETTI-ART",
               "descrizione": "Rinderfilet mit seinem Bratenjus, Topinambur-Creme, in Valcalepio pochierte Birne, Lardo, der auf dem Filet schmilzt, und frisch geriebener schwarzer Trüffel.",
               "tag": ['GF', 'LFO']},
        "uk": {"titolo": "ЯЛОВИЧЕ ФІЛЕ А-ЛЯ ДОНІЦЕТТІ",
               "descrizione": "Яловиче філе з власним соусом, крем із топінамбура, груша, томлена у вині Valcalepio, лардо, що тане на філе, і тертий чорний трюфель.",
               "tag": ['БГ', 'ОБЛ']},
    },
    {
        "sezione": "secondi",
        "prezzo": "28",
        "tag": ['NG'],
        "it": {"titolo": "OSSOBUCO DI VITELLO CON PURÈ",
               "descrizione": "Dalla tradizione lombarda l’ossobuco di vitello lungamente cotto. Servito con la tipica gremolada fatta con prezzemolo, limone e un pizzico di aglio."},
        "en": {"titolo": "VEAL OSSOBUCO WITH MASHED POTATO",
               "descrizione": "From the Lombard tradition, veal ossobuco cooked long and slow. Served with the classic gremolada of parsley, lemon and a hint of garlic.",
               "tag": ['GF']},
        "fr": {"titolo": "OSSOBUCO DE VEAU ET PURÉE",
               "descrizione": "Venu de la tradition lombarde, l’ossobuco de veau longuement cuit. Servi avec la traditionnelle gremolada au persil, citron et une pointe d’ail.",
               "tag": ['SG']},
        "es": {"titolo": "OSSOBUCO DE TERNERA CON PURÉ",
               "descrizione": "De la tradición lombarda, el ossobuco de ternera largamente cocinado. Servido con la típica gremolada de perejil, limón y una pizca de ajo.",
               "tag": ['SG']},
        "de": {"titolo": "OSSOBUCO VOM KALB MIT KARTOFFELPÜREE",
               "descrizione": "Aus der lombardischen Tradition: lange geschmorte Kalbshaxenscheibe. Serviert mit der typischen Gremolada aus Petersilie, Zitrone und einem Hauch Knoblauch.",
               "tag": ['GF']},
        "uk": {"titolo": "ТЕЛЯЧЕ ОСОБУКО З ПЮРЕ",
               "descrizione": "З ломбардської традиції: теляче особуко тривалого томління. Подаємо з класичною гремоладою з петрушки, лимона й дрібки часнику.",
               "tag": ['БГ']},
    },
    {
        "sezione": "secondi",
        "prezzo": "35",
        "tag": ['NG'],
        "it": {"titolo": "VUOI UN PIATTO UNICO CON OSSOBUCO E RISOTTO GIALLO?",
               "descrizione": "Opzione per accontentare i più golosi con il piatto completo con risotto milanese e l’ossobuco in gremolada."},
        "en": {"titolo": "FANCY IT ALL ON ONE PLATE, OSSOBUCO AND SAFFRON RISOTTO?",
               "descrizione": "For the greediest among you: the full plate, with risotto alla milanese and the ossobuco in its gremolada.",
               "tag": ['GF']},
        "fr": {"titolo": "ENVIE DU PLAT COMPLET, OSSOBUCO ET RISOTTO SAFRANÉ ?",
               "descrizione": "L’option pour les plus gourmands : l’assiette complète, avec risotto à la milanaise et l’ossobuco en gremolada.",
               "tag": ['SG']},
        "es": {"titolo": "¿QUIERES EL PLATO ÚNICO, OSSOBUCO Y RISOTTO AL AZAFRÁN?",
               "descrizione": "La opción para los más golosos: el plato completo, con risotto a la milanesa y el ossobuco en gremolada.",
               "tag": ['SG']},
        "de": {"titolo": "LIEBER ALLES AUF EINEM TELLER, OSSOBUCO UND SAFRANRISOTTO?",
               "descrizione": "Für die Hungrigsten: der komplette Teller, mit Risotto alla milanese und dem Ossobuco in seiner Gremolada.",
               "tag": ['GF']},
        "uk": {"titolo": "ХОЧЕТЕ ВСЕ В ОДНІЙ ТАРІЛЦІ — ОСОБУКО Й ШАФРАНОВЕ РИЗОТО?",
               "descrizione": "Для найласіших: повна тарілка з ризото по-міланськи й особуко в гремоладі.",
               "tag": ['БГ']},
    },
    {
        "sezione": "secondi",
        "prezzo": "24",
        "tag": ['NG'],
        "it": {"titolo": "GUANCETTA DI MAIALINO BRASATA E POLENTA",
               "descrizione": "Cotta 36 ore, tenera e succulenta che profuma di vino e di casa."},
        "en": {"titolo": "BRAISED SUCKLING PIG CHEEK AND POLENTA",
               "descrizione": "Cooked for 36 hours, tender and succulent, with the scent of wine and of home.",
               "tag": ['GF']},
        "fr": {"titolo": "JOUE DE PORCELET BRAISÉE ET POLENTA",
               "descrizione": "Cuite 36 heures, tendre et fondante, elle sent le vin et la maison.",
               "tag": ['SG']},
        "es": {"titolo": "CARRILLERA DE CERDO BRASEADA Y POLENTA",
               "descrizione": "Cocinada 36 horas, tierna y jugosa, huele a vino y a casa.",
               "tag": ['SG']},
        "de": {"titolo": "GESCHMORTE SPANFERKELBACKE UND POLENTA",
               "descrizione": "36 Stunden gegart, zart und saftig, sie duftet nach Wein und nach Zuhause.",
               "tag": ['GF']},
        "uk": {"titolo": "ТУШКОВАНА ЩІЧКА ПОРОСЯТИ Й ПОЛЕНТА",
               "descrizione": "Готується 36 годин: ніжна й соковита, пахне вином і домом.",
               "tag": ['БГ']},
    },
    {
        "sezione": "secondi",
        "prezzo": "24",
        "tag": ['NG'],
        "it": {"titolo": "CONIGLIO ALLA BERGAMASCA",
               "descrizione": "Il coniglio come si fa nelle nostre valli: rosolato con pancetta, rosmarino e una sfumata di bianco, finito al forno. Con la polenta nostrana, ovviamente."},
        "en": {"titolo": "RABBIT THE BERGAMO WAY",
               "descrizione": "Rabbit the way they make it up in our valleys: browned with pancetta and rosemary, a splash of white wine, then finished in the oven. With our own polenta, of course.",
               "tag": ['GF']},
        "fr": {"titolo": "LAPIN À LA BERGAMASQUE",
               "descrizione": "Le lapin comme on le fait dans nos vallées : rissolé avec de la pancetta et du romarin, déglacé au vin blanc, fini au four. Avec la polenta maison, évidemment.",
               "tag": ['SG']},
        "es": {"titolo": "CONEJO A LA BERGAMASCA",
               "descrizione": "El conejo como se hace en nuestros valles: dorado con panceta y romero, desglasado con vino blanco y acabado al horno. Con polenta casera, por supuesto.",
               "tag": ['SG']},
        "de": {"titolo": "KANINCHEN AUF BERGAMASKER ART",
               "descrizione": "Kaninchen, wie man es in unseren Tälern macht: mit Pancetta und Rosmarin angebraten, mit Weißwein abgelöscht, im Ofen fertig gegart. Mit Polenta nach Hausart, versteht sich.",
               "tag": ['GF']},
        "uk": {"titolo": "КРОЛИК ПО-БЕРГАМСЬКИ",
               "descrizione": "Кролик так, як його роблять у наших долинах: підсмажений із панчеттою й розмарином, збризнутий білим вином і доведений до готовності в духовці. З домашньою полентою, звісно.",
               "tag": ['БГ']},
    },
    {
        "sezione": "secondi",
        "prezzo": "24",
        "tag": ['NG'],
        "it": {"titolo": "ROGNONE DI VITELLO TRIFOLATO CON I FUNGHI DEL BOSCO",
               "descrizione": "Rognone di vitello saltato al momento, con aglio, prezzemolo, una sfumata di vino e i funghi che il bosco ci dà in quel momento. Servito sul purè."},
        "en": {"titolo": "SAUTÉED VEAL KIDNEY WITH WILD MUSHROOMS",
               "descrizione": "Veal kidney sautéed to order with garlic, parsley, a splash of wine and whatever mushrooms the woods are giving us at the moment. Served on mashed potato.",
               "tag": ['GF']},
        "fr": {"titolo": "ROGNON DE VEAU POÊLÉ AUX CHAMPIGNONS DES BOIS",
               "descrizione": "Rognon de veau sauté à la minute, avec ail, persil, un trait de vin et les champignons que le bois nous offre à ce moment-là. Servi sur une purée.",
               "tag": ['SG']},
        "es": {"titolo": "RIÑÓN DE TERNERA SALTEADO CON SETAS DEL BOSQUE",
               "descrizione": "Riñón de ternera salteado al momento con ajo, perejil, un chorrito de vino y las setas que el bosque nos da en ese momento. Servido sobre puré.",
               "tag": ['SG']},
        "de": {"titolo": "KALBSNIERE MIT WALDPILZEN",
               "descrizione": "Kalbsniere, frisch in der Pfanne gebraten, mit Knoblauch, Petersilie, einem Schuss Wein und den Pilzen, die uns der Wald gerade schenkt. Serviert auf Kartoffelpüree.",
               "tag": ['GF']},
        "uk": {"titolo": "ТЕЛЯЧІ НИРКИ З ЛІСОВИМИ ГРИБАМИ",
               "descrizione": "Телячі нирки, обсмажені на замовлення з часником, петрушкою, краплею вина та тими грибами, які ліс дарує нам саме зараз. Подаються на пюре.",
               "tag": ['БГ']},
    },
    {
        "sezione": "secondi",
        "prezzo": "26",
        "tag": ['NG'],
        "it": {"titolo": "PESCATO DEL GIORNO",
               "descrizione": "Chiedici come l’abbiamo cucinato oggi."},
        "en": {"titolo": "TODAY’S CATCH",
               "descrizione": "Ask us how we have cooked it today.",
               "tag": ['GF']},
        "fr": {"titolo": "POISSON DU JOUR",
               "descrizione": "Demandez-nous comment nous l’avons cuisiné aujourd’hui.",
               "tag": ['SG']},
        "es": {"titolo": "PESCADO DEL DÍA",
               "descrizione": "Pregúntanos cómo lo hemos cocinado hoy.",
               "tag": ['SG']},
        "de": {"titolo": "FANG DES TAGES",
               "descrizione": "Fragen Sie uns, wie wir ihn heute zubereitet haben.",
               "tag": ['GF']},
        "uk": {"titolo": "УЛОВ ДНЯ",
               "descrizione": "Запитайте нас, як ми його приготували сьогодні.",
               "tag": ['БГ']},
    },
    # ── contorni ──────────────────────────────────────────────────
    {
        "sezione": "contorni",
        "prezzo": "4",
        "tag": [],
        "it": {"titolo": "POLENTA NOSTRANA",
               "descrizione": None},
        "en": {"titolo": "OUR OWN POLENTA",
               "descrizione": None,
               "tag": []},
        "fr": {"titolo": "POLENTA MAISON",
               "descrizione": None,
               "tag": []},
        "es": {"titolo": "POLENTA CASERA",
               "descrizione": None,
               "tag": []},
        "de": {"titolo": "POLENTA NACH HAUSART",
               "descrizione": None,
               "tag": []},
        "uk": {"titolo": "ДОМАШНЯ ПОЛЕНТА",
               "descrizione": None,
               "tag": []},
    },
    {
        "sezione": "contorni",
        "prezzo": "8",
        "tag": [],
        "it": {"titolo": "ASSAGGIO DI SUA MAESTÀ LA TARAGNA",
               "descrizione": None},
        "en": {"titolo": "A TASTE OF HER MAJESTY LA TARAGNA",
               "descrizione": None,
               "tag": []},
        "fr": {"titolo": "UNE BOUCHÉE DE SA MAJESTÉ LA TARAGNA",
               "descrizione": None,
               "tag": []},
        "es": {"titolo": "UN BOCADO DE SU MAJESTAD LA TARAGNA",
               "descrizione": None,
               "tag": []},
        "de": {"titolo": "KOSTPROBE VON IHRER MAJESTÄT LA TARAGNA",
               "descrizione": None,
               "tag": []},
        "uk": {"titolo": "ПОРЦІЯ ЇЇ ВЕЛИЧНОСТІ ЛА ТАРАНЬЇ",
               "descrizione": None,
               "tag": []},
    },
    {
        "sezione": "contorni",
        "prezzo": "6",
        "tag": [],
        "it": {"titolo": "PURÈ DI PATATE CREMOSISSIMO",
               "descrizione": None},
        "en": {"titolo": "THE CREAMIEST MASHED POTATO",
               "descrizione": None,
               "tag": []},
        "fr": {"titolo": "PURÉE DE POMMES DE TERRE ULTRA-CRÉMEUSE",
               "descrizione": None,
               "tag": []},
        "es": {"titolo": "PURÉ DE PATATA CREMOSÍSIMO",
               "descrizione": None,
               "tag": []},
        "de": {"titolo": "BESONDERS CREMIGES KARTOFFELPÜREE",
               "descrizione": None,
               "tag": []},
        "uk": {"titolo": "НАЙНІЖНІШЕ КАРТОПЛЯНЕ ПЮРЕ",
               "descrizione": None,
               "tag": []},
    },
    {
        "sezione": "contorni",
        "prezzo": "6",
        "tag": [],
        "it": {"titolo": "PATATE ARROSTO",
               "descrizione": None},
        "en": {"titolo": "ROAST POTATOES",
               "descrizione": None,
               "tag": []},
        "fr": {"titolo": "POMMES DE TERRE RÔTIES",
               "descrizione": None,
               "tag": []},
        "es": {"titolo": "PATATAS ASADAS",
               "descrizione": None,
               "tag": []},
        "de": {"titolo": "RÖSTKARTOFFELN",
               "descrizione": None,
               "tag": []},
        "uk": {"titolo": "ЗАПЕЧЕНА КАРТОПЛЯ",
               "descrizione": None,
               "tag": []},
    },
    {
        "sezione": "contorni",
        "prezzo": "6",
        "tag": [],
        "it": {"titolo": "SPADELLATA DI VERDURE",
               "descrizione": None},
        "en": {"titolo": "PAN-TOSSED VEGETABLES",
               "descrizione": None,
               "tag": []},
        "fr": {"titolo": "POÊLÉE DE LÉGUMES",
               "descrizione": None,
               "tag": []},
        "es": {"titolo": "SALTEADO DE VERDURAS",
               "descrizione": None,
               "tag": []},
        "de": {"titolo": "GEMÜSE AUS DER PFANNE",
               "descrizione": None,
               "tag": []},
        "uk": {"titolo": "ОВОЧІ НА СКОВОРІДЦІ",
               "descrizione": None,
               "tag": []},
    },
    {
        "sezione": "contorni",
        "prezzo": "6",
        "tag": [],
        "it": {"titolo": "GIARDINIERA DI VERDURE",
               "descrizione": None},
        "en": {"titolo": "GIARDINIERA, OUR PICKLED VEGETABLES",
               "descrizione": None,
               "tag": []},
        "fr": {"titolo": "GIARDINIERA DE LÉGUMES",
               "descrizione": None,
               "tag": []},
        "es": {"titolo": "GIARDINIERA DE VERDURAS",
               "descrizione": None,
               "tag": []},
        "de": {"titolo": "GIARDINIERA, EINGELEGTES GEMÜSE",
               "descrizione": None,
               "tag": []},
        "uk": {"titolo": "ДЖАРДІНЬЄРА, МАРИНОВАНІ ОВОЧІ",
               "descrizione": None,
               "tag": []},
    },
    {
        "sezione": "contorni",
        "prezzo": "6",
        "tag": [],
        "it": {"titolo": "INSALATA MISTA DI STAGIONE",
               "descrizione": None},
        "en": {"titolo": "SEASONAL MIXED SALAD",
               "descrizione": None,
               "tag": []},
        "fr": {"titolo": "SALADE MIXTE DE SAISON",
               "descrizione": None,
               "tag": []},
        "es": {"titolo": "ENSALADA MIXTA DE TEMPORADA",
               "descrizione": None,
               "tag": []},
        "de": {"titolo": "GEMISCHTER SAISONSALAT",
               "descrizione": None,
               "tag": []},
        "uk": {"titolo": "МІШАНИЙ СЕЗОННИЙ САЛАТ",
               "descrizione": None,
               "tag": []},
    },
    # ── dolci ─────────────────────────────────────────────────────
    {
        "sezione": "dolci",
        "prezzo": "10",
        "tag": ['NG'],
        "it": {"titolo": "LA PIANTINA DEL TIRAMISÙ",
               "descrizione": "Il nostro dolce più antico in carta dal primo giorno, servito in maniera particolare. Definito da molti il miglior tiramisù mai assaggiato. Non fartelo scappare!"},
        "en": {"titolo": "THE TIRAMISÙ IN A PLANT POT",
               "descrizione": "Our oldest dessert, on the menu since day one, served in a rather particular way. Many have called it the best tiramisù they have ever eaten. Don’t miss out!",
               "tag": ['GF']},
        "fr": {"titolo": "LE TIRAMISÙ EN POT DE FLEURS",
               "descrizione": "Notre dessert le plus ancien, à la carte depuis le premier jour, servi d’une façon bien à lui. Beaucoup disent que c’est le meilleur tiramisù qu’ils aient jamais goûté. Ne le laissez pas filer !",
               "tag": ['SG']},
        "es": {"titolo": "LA MACETITA DE TIRAMISÙ",
               "descrizione": "Nuestro postre más antiguo, en carta desde el primer día, servido de una manera muy particular. Muchos lo definen como el mejor tiramisù que han probado. ¡No lo dejes escapar!",
               "tag": ['SG']},
        "de": {"titolo": "DAS TIRAMISÙ IM BLUMENTOPF",
               "descrizione": "Unser ältestes Dessert, seit dem ersten Tag auf der Karte, auf ganz besondere Weise serviert. Viele nennen es das beste Tiramisù, das sie je gegessen haben. Lassen Sie es sich nicht entgehen!",
               "tag": ['GF']},
        "uk": {"titolo": "ТИРАМІСУ В ГОРЩИКУ",
               "descrizione": "Наш найдавніший десерт — у меню з першого дня, подається у зовсім особливий спосіб. Багато хто називає його найкращим тирамісу у своєму житті. Не проґавте!",
               "tag": ['БГ']},
    },
    {
        "sezione": "dolci",
        "prezzo": "9",
        "tag": ['NG'],
        "it": {"titolo": "CHEESECAKE AI FRUTTI DI BOSCO",
               "descrizione": "La nostra versione di una New York Cheesecake in chiave bergamasca, dentro non troverai la Philadelphia ma un mix di formaggi freschi locali. Sopra, a dare gusto, le salse ai frutti di bosco e un coulis al lampone che produciamo noi."},
        "en": {"titolo": "BERRY CHEESECAKE",
               "descrizione": "Our version of a New York cheesecake with a Bergamo twist: no Philadelphia inside, but a blend of fresh local cheeses. On top, berry sauces and a raspberry coulis we make ourselves.",
               "tag": ['GF']},
        "fr": {"titolo": "CHEESECAKE AUX FRUITS DES BOIS",
               "descrizione": "Notre version du New York cheesecake revisitée à la bergamasque : à l’intérieur, pas de Philadelphia mais un mélange de fromages frais locaux. Dessus, des sauces aux fruits des bois et un coulis de framboise que nous produisons nous-mêmes.",
               "tag": ['SG']},
        "es": {"titolo": "CHEESECAKE DE FRUTOS ROJOS",
               "descrizione": "Nuestra versión de la New York cheesecake en clave bergamasca: dentro no encontrarás Philadelphia, sino una mezcla de quesos frescos locales. Encima, salsas de frutos rojos y un coulis de frambuesa que hacemos nosotros.",
               "tag": ['SG']},
        "de": {"titolo": "CHEESECAKE MIT WALDBEEREN",
               "descrizione": "Unsere Version des New York Cheesecakes auf Bergamasker Art: innen kein Philadelphia, sondern eine Mischung frischer Käse von hier. Darauf Waldbeersaucen und ein Himbeercoulis aus eigener Herstellung.",
               "tag": ['GF']},
        "uk": {"titolo": "ЧИЗКЕЙК ІЗ ЛІСОВИМИ ЯГОДАМИ",
               "descrizione": "Наша версія нью-йоркського чизкейка по-бергамськи: усередині не Philadelphia, а суміш місцевих свіжих сирів. Зверху — соуси з лісових ягід і малиновий кулі власного виробництва.",
               "tag": ['БГ']},
    },
    {
        "sezione": "dolci",
        "prezzo": "9",
        "tag": ['NG', 'NL'],
        "it": {"titolo": "TI RICORDI IL “SOLERO”?",
               "descrizione": "Semifreddo al cocco, servito su passion fruit, tapioca esplosiva, salsa al cocco ed olio al basilico. Un dolce che ti riporterà agli anni ‘80 con il classico gelato Algida."},
        "en": {"titolo": "REMEMBER THE “SOLERO”?",
               "descrizione": "Coconut semifreddo served on passion fruit, popping tapioca, coconut sauce and basil oil. A dessert that will take you straight back to the eighties and the classic Solero ice lolly.",
               "tag": ['GF', 'LF']},
        "fr": {"titolo": "VOUS VOUS SOUVENEZ DU « SOLERO » ?",
               "descrizione": "Semifreddo à la noix de coco servi sur fruit de la passion, tapioca explosif, sauce coco et huile de basilic. Un dessert qui vous ramènera droit aux années 80, au temps du fameux Solero.",
               "tag": ['SG', 'SL']},
        "es": {"titolo": "¿TE ACUERDAS DEL «SOLERO»?",
               "descrizione": "Semifrío de coco sobre fruta de la pasión, tapioca explosiva, salsa de coco y aceite de albahaca. Un postre que te llevará de vuelta a los años 80 y al clásico helado de Frigo.",
               "tag": ['SG', 'SL']},
        "de": {"titolo": "ERINNERN SIE SICH AN „SOLERO“?",
               "descrizione": "Kokos-Semifreddo auf Passionsfrucht, knisternde Tapioka, Kokossauce und Basilikumöl. Ein Dessert, das Sie direkt in die Achtziger zurückbringt – zum klassischen Solero-Eis.",
               "tag": ['GF', 'LF']},
        "uk": {"titolo": "ПАМ’ЯТАЄТЕ «SOLERO»?",
               "descrizione": "Кокосове семіфреддо на маракуї, тапіока, що вибухає в роті, кокосовий соус і базилікова олія. Десерт, який поверне вас просто у вісімдесяті — до культового морозива Algida.",
               "tag": ['БГ', 'БЛ']},
    },
    {
        "sezione": "dolci",
        "prezzo": "9",
        "tag": ['NG'],
        "it": {"titolo": "PANNA COTTA DELL’INGEGNER DANISI",
               "descrizione": "La panna cotta è un classico delle Osterie, non poteva mancare tra i nostri dolci! L’abbiamo dedicata ad un nostro caro ospite che ci ha esortato più e più volte a farla, migliorando e perfezionando la ricetta fino alla versione attuale. Quasi perfetta. Sceglila alle AMARENE FABBRI, al CARAMELLO oppure al CIOCCOLATO FUSO."},
        "en": {"titolo": "PANNA COTTA FOR MR DANISI, THE ENGINEER",
               "descrizione": "Panna cotta is an osteria classic — it could hardly be missing from our list. We have dedicated it to a dear guest who urged us again and again to make it, improving and refining the recipe up to the version you have today. Almost perfect. Choose it with AMARENA FABBRI cherries, with CARAMEL or with MELTED CHOCOLATE.",
               "tag": ['GF']},
        "fr": {"titolo": "LA PANNA COTTA DE L’INGÉNIEUR DANISI",
               "descrizione": "La panna cotta est un classique des osterie, elle ne pouvait pas manquer ici. Nous l’avons dédiée à un client qui nous est cher et qui nous a poussés encore et encore à la faire, en améliorant et en affinant la recette jusqu’à la version d’aujourd’hui. Presque parfaite. À choisir aux AMARENA FABBRI, au CARAMEL ou au CHOCOLAT FONDU.",
               "tag": ['SG']},
        "es": {"titolo": "LA PANNA COTTA DEL INGENIERO DANISI",
               "descrizione": "La panna cotta es un clásico de las osterie, ¡no podía faltar entre nuestros postres! Se la dedicamos a un cliente muy querido que nos insistió una y otra vez para que la hiciéramos, mejorando y afinando la receta hasta la versión de hoy. Casi perfecta. Elígela con AMARENA FABBRI, con CARAMELO o con CHOCOLATE FUNDIDO.",
               "tag": ['SG']},
        "de": {"titolo": "DIE PANNA COTTA VON INGENIEUR DANISI",
               "descrizione": "Panna cotta ist ein Klassiker der Osterien, sie durfte auf unserer Karte nicht fehlen! Wir haben sie einem lieben Gast gewidmet, der uns immer wieder gedrängt hat, sie zu machen; das Rezept wurde dabei so lange verfeinert, bis es bei der heutigen Fassung ankam. Fast perfekt. Zur Wahl mit AMARENA FABBRI, mit KARAMELL oder mit GESCHMOLZENER SCHOKOLADE.",
               "tag": ['GF']},
        "uk": {"titolo": "ПАНАКОТА ВІД ІНЖЕНЕРА ДАНІЗІ",
               "descrizione": "Панакота — класика остерій, вона не могла не з’явитися в нашому меню. Ми присвятили її дорогому гостеві, який знову й знову підштовхував нас її зробити, а рецепт удосконалювався до сьогоднішньої версії. Майже досконала. Оберіть її з вишнею AMARENA FABBRI, з карамеллю або з розтопленим шоколадом.",
               "tag": ['БГ']},
    },
    {
        "sezione": "dolci",
        "prezzo": "10",
        "tag": ['NG'],
        "it": {"titolo": "“LUCIA DI LAMMERMOOR”",
               "descrizione": "Semifreddo alla vaniglia, clementine caramellate, gel di melograno e amaretti. Per l’opera più celebre di Donizetti, che cantava Nellie Melba, la stessa della Pesca Melba, e per la nostra Santa Lucia, che la notte del 12 dicembre lascia ai bambini bergamaschi gli agrumi d’inverno."},
        "en": {"titolo": "“LUCIA DI LAMMERMOOR”",
               "descrizione": "Vanilla semifreddo, caramelised clementines, pomegranate gel and amaretti. For Donizetti’s most celebrated opera, sung by Nellie Melba — the same Melba as Peach Melba — and for our own Santa Lucia, who on the night of 12 December leaves the children of Bergamo the citrus fruits of winter.",
               "tag": ['GF']},
        "fr": {"titolo": "« LUCIA DI LAMMERMOOR »",
               "descrizione": "Semifreddo à la vanille, clémentines caramélisées, gel de grenade et amaretti. Pour l’opéra le plus célèbre de Donizetti, que chantait Nellie Melba — celle de la pêche Melba — et pour notre Sainte Lucie, qui dans la nuit du 12 décembre apporte aux enfants de Bergame les agrumes de l’hiver.",
               "tag": ['SG']},
        "es": {"titolo": "«LUCIA DI LAMMERMOOR»",
               "descrizione": "Semifreddo de vainilla, clementinas caramelizadas, gel de granada y amaretti. Por la ópera más célebre de Donizetti, que cantaba Nellie Melba —la misma del melocotón Melba— y por nuestra Santa Lucía, que la noche del 12 de diciembre deja a los niños de Bérgamo los cítricos del invierno.",
               "tag": ['SG']},
        "de": {"titolo": "„LUCIA DI LAMMERMOOR“",
               "descrizione": "Vanille-Semifreddo, karamellisierte Clementinen, Granatapfel-Gel und Amaretti. Für Donizettis berühmteste Oper, in der Nellie Melba sang – dieselbe Melba wie beim Pfirsich Melba –, und für unsere Santa Lucia, die in der Nacht des 12. Dezember den Kindern Bergamos die Zitrusfrüchte des Winters bringt.",
               "tag": ['GF']},
        "uk": {"titolo": "«ЛЮЧІЯ ДІ ЛАММЕРМУР»",
               "descrizione": "Ванільне семіфредо, карамелізовані клементини, гель із граната та амаретті. На честь найвідомішої опери Доніцетті, у якій співала Неллі Мельба — та сама, що й у «Персику Мельба», — і нашої Святої Лючії, яка в ніч 12 грудня приносить бергамським дітям зимові цитрусові.",
               "tag": ['БГ']},
    },
    {
        "sezione": "dolci",
        "prezzo": "10",
        "tag": ['NG'],
        "it": {"titolo": "TORTA DI NOCCIOLE, CIOCCOLATO FONDENTE E ZABAIONE AL MOSCATO DI SCANZO",
               "descrizione": "Torta di nocciole servita tiepida, con un velo di cioccolato fondente amaro, sale in fiocchi e uno zabaione al Moscato di Scanzo montato al momento."},
        "en": {"titolo": "HAZELNUT CAKE, DARK CHOCOLATE AND MOSCATO DI SCANZO ZABAIONE",
               "descrizione": "Hazelnut cake served warm, with a thin layer of bitter dark chocolate, salt flakes and a Moscato di Scanzo zabaione whisked to order.",
               "tag": ['GF']},
        "fr": {"titolo": "GÂTEAU AUX NOISETTES, CHOCOLAT NOIR ET SABAYON AU MOSCATO DI SCANZO",
               "descrizione": "Gâteau aux noisettes servi tiède, avec un voile de chocolat noir amer, du sel en flocons et un sabayon au Moscato di Scanzo monté à la minute.",
               "tag": ['SG']},
        "es": {"titolo": "TARTA DE AVELLANAS, CHOCOLATE NEGRO Y SABAYÓN DE MOSCATO DI SCANZO",
               "descrizione": "Tarta de avellanas servida templada, con un velo de chocolate negro amargo, sal en escamas y un sabayón de Moscato di Scanzo montado al momento.",
               "tag": ['SG']},
        "de": {"titolo": "HASELNUSSKUCHEN, ZARTBITTERSCHOKOLADE UND ZABAIONE MIT MOSCATO DI SCANZO",
               "descrizione": "Haselnusskuchen, lauwarm serviert, mit einem Hauch herber Zartbitterschokolade, Salzflocken und einer frisch aufgeschlagenen Zabaione mit Moscato di Scanzo.",
               "tag": ['GF']},
        "uk": {"titolo": "ТОРТ ІЗ ФУНДУКА, ЧОРНИЙ ШОКОЛАД І САБАЙОН ІЗ МОСКАТО ДІ СКАНЦО",
               "descrizione": "Торт із фундука, який подаємо теплим, із тонким шаром гіркого чорного шоколаду, пластівцями солі та сабайоном на Moscato di Scanzo, збитим на замовлення.",
               "tag": ['БГ']},
    },
]

DEGUSTAZIONI = [
    {
        "prezzo": "60",
        "it": {"nome": "DEGUSTAZIONE",
               "sottotitolo": "“Prima volta”",
               "intro": "Per la prima volta nella nostra osteria ti consigliamo di assaggiare il meglio della cucina Bergamasca nella nostra interpretazione! Il metodo migliore per conoscerci.",
               "note": "Le degustazioni sono da considerarsi per tutto il tavolo. Fatte salve allergie e intolleranze, per le quali proporremo alternative.",
               "steps": ['ANTIPASTO MISTO DELL’OSTERIA', 'CASONCELLI DI MAMMA E PAPÀ', 'CONIGLIO O GUANCETTA a tua scelta', 'DOLCE A SCELTA']},
        "en": {"nome": "TASTING MENU",
               "sottotitolo": "“First time”",
               "intro": "If this is your first time in our osteria, we suggest you taste the best of Bergamasque cooking in our own interpretation. It is the finest way to get to know us.",
               "note": "Tasting menus are intended for the whole table. Allergies and intolerances are the one exception — for those we will gladly suggest an alternative.",
               "steps": ['THE OSTERIA’S MIXED ANTIPASTO', 'MAMMA AND PAPÀ’S CASONCELLI', 'RABBIT OR SUCKLING PIG CHEEK, as you prefer', 'DESSERT OF YOUR CHOICE']},
        "fr": {"nome": "DÉGUSTATION",
               "sottotitolo": "« Première fois »",
               "intro": "Pour votre première fois dans notre osteria, nous vous conseillons de goûter le meilleur de la cuisine bergamasque dans notre interprétation. La plus belle façon de faire connaissance.",
               "note": "Les menus dégustation sont servis pour l’ensemble de la table. Allergies et intolérances exceptées : nous vous proposerons volontiers une alternative.",
               "steps": ['L’ASSORTIMENT D’ANTIPASTI DE L’OSTERIA', 'LES CASONCELLI DE MAMAN ET PAPA', 'LAPIN OU JOUE DE PORCELET, au choix', 'DESSERT AU CHOIX']},
        "es": {"nome": "DEGUSTACIÓN",
               "sottotitolo": "«Primera vez»",
               "intro": "Si es tu primera vez en nuestra osteria, te aconsejamos probar lo mejor de la cocina bergamasca en nuestra interpretación. La mejor manera de conocernos.",
               "note": "Los menús degustación son para toda la mesa. Salvo alergias e intolerancias, para las que propondremos alternativas.",
               "steps": ['ENTRANTE MIXTO DE LA OSTERIA', 'LOS CASONCELLI DE MAMÁ Y PAPÁ', 'CONEJO O CARRILLERA, a tu elección', 'POSTRE A ELEGIR']},
        "de": {"nome": "DEGUSTATIONSMENÜ",
               "sottotitolo": "„Das erste Mal“",
               "intro": "Wenn Sie zum ersten Mal in unserer Osteria sind, empfehlen wir Ihnen das Beste der Bergamasker Küche in unserer Auslegung. Der schönste Weg, uns kennenzulernen.",
               "note": "Die Degustationsmenüs gelten für den ganzen Tisch. Ausgenommen sind Allergien und Unverträglichkeiten – dafür schlagen wir Ihnen gerne Alternativen vor.",
               "steps": ['GEMISCHTE VORSPEISENPLATTE DER OSTERIA', 'CASONCELLI VON MAMMA UND PAPÀ', 'KANINCHEN ODER SPANFERKELBACKE, nach Wahl', 'DESSERT NACH WAHL']},
        "uk": {"nome": "ДЕГУСТАЦІЯ",
               "sottotitolo": "«Перший раз»",
               "intro": "Якщо ви в нашій остерії вперше, радимо скуштувати найкраще з бергамської кухні в нашому прочитанні. Це найліпший спосіб із нами познайомитися.",
               "note": "Дегустаційні меню замовляються на весь стіл. Виняток — алергії та харчова непереносимість: у таких випадках ми запропонуємо альтернативи.",
               "steps": ['АСОРТІ ЗАКУСОК ОСТЕРІЇ', 'CASONCELLI МАМИ Й ТАТА', 'КРОЛИК АБО ЩІЧКА ПОРОСЯТИ, на ваш вибір', 'ДЕСЕРТ НА ВИБІР']},
    },
    {
        "prezzo": "75",
        "it": {"nome": "DEGUSTAZIONE",
               "sottotitolo": "“Fidati dell’oste”",
               "intro": "I piatti consigliati dall’Oste, quelli che rappresentano la stagione ed il momento. Molto spesso con variazioni raccontate a voce.",
               "note": "Le degustazioni sono da considerarsi per tutto il tavolo. Fatte salve allergie e intolleranze, per le quali proporremo alternative.",
               "steps": ['BATTUTA DI MANZO, PORCINI E NOCCIOLA', 'ROSA DI ZUCCA', 'RISOTTO ALLO STRACCHINO ALL’ANTICA E MELA KISSABEL', 'ANATRA, BARBABIETOLA, ROSA CANINA E CAFFÈ', 'DOLCE A SCELTA']},
        "en": {"nome": "TASTING MENU",
               "sottotitolo": "“Trust the oste”",
               "intro": "The dishes the Oste recommends, the ones that speak of the season and of the moment. Very often with variations told to you at the table.",
               "note": "Tasting menus are intended for the whole table. Allergies and intolerances are the one exception — for those we will gladly suggest an alternative.",
               "steps": ['HAND-CUT BEEF TARTARE, PORCINI AND HAZELNUT', 'PUMPKIN ROSE', 'RISOTTO WITH STRACCHINO ALL’ANTICA AND KISSABEL APPLE', 'DUCK, BEETROOT, ROSEHIP AND COFFEE', 'DESSERT OF YOUR CHOICE']},
        "fr": {"nome": "DÉGUSTATION",
               "sottotitolo": "« Faites confiance à l’oste »",
               "intro": "Les plats conseillés par l’Oste, ceux qui représentent la saison et le moment. Très souvent avec des variations racontées de vive voix.",
               "note": "Les menus dégustation sont servis pour l’ensemble de la table. Allergies et intolérances exceptées : nous vous proposerons volontiers une alternative.",
               "steps": ['TARTARE DE BŒUF, CÈPES ET NOISETTE', 'ROSE DE COURGE', 'RISOTTO AU STRACCHINO ALL’ANTICA ET POMME KISSABEL', 'CANARD, BETTERAVE, ÉGLANTIER ET CAFÉ', 'DESSERT AU CHOIX']},
        "es": {"nome": "DEGUSTACIÓN",
               "sottotitolo": "«Fíate del oste»",
               "intro": "Los platos que recomienda el Oste, los que representan la temporada y el momento. Muy a menudo con variaciones contadas de viva voz.",
               "note": "Los menús degustación son para toda la mesa. Salvo alergias e intolerancias, para las que propondremos alternativas.",
               "steps": ['TARTAR DE VACUNO, BOLETUS Y AVELLANA', 'ROSA DE CALABAZA', 'RISOTTO DE STRACCHINO ALL’ANTICA Y MANZANA KISSABEL', 'PATO, REMOLACHA, ESCARAMUJO Y CAFÉ', 'POSTRE A ELEGIR']},
        "de": {"nome": "DEGUSTATIONSMENÜ",
               "sottotitolo": "„Vertrauen Sie dem Oste“",
               "intro": "Die Gerichte, die der <i>Oste</i> empfiehlt: jene, die für die Saison und den Moment stehen. Sehr oft mit Abwandlungen, die wir Ihnen am Tisch erzählen.",
               "note": "Die Degustationsmenüs gelten für den ganzen Tisch. Ausgenommen sind Allergien und Unverträglichkeiten – dafür schlagen wir Ihnen gerne Alternativen vor.",
               "steps": ['TATAR VOM RIND, STEINPILZE UND HASELNUSS', 'KÜRBISROSE', 'RISOTTO MIT STRACCHINO ALL’ANTICA UND KISSABEL-APFEL', 'ENTE, ROTE BETE, HAGEBUTTE UND KAFFEE', 'DESSERT NACH WAHL']},
        "uk": {"nome": "ДЕГУСТАЦІЯ",
               "sottotitolo": "«Довіртеся oste»",
               "intro": "Страви, які радить oste, — ті, що передають сезон і момент. Дуже часто з варіаціями, про які ми розповідаємо за столом.",
               "note": "Дегустаційні меню замовляються на весь стіл. Виняток — алергії та харчова непереносимість: у таких випадках ми запропонуємо альтернативи.",
               "steps": ['ТАРТАР ІЗ ЯЛОВИЧИНИ, БІЛІ ГРИБИ ТА ФУНДУК', 'ГАРБУЗОВА ТРОЯНДА', 'РИЗОТО ЗІ СТРАККІНО ALL’ANTICA ТА ЯБЛУКОМ KISSABEL', 'КАЧКА, БУРЯК, ШИПШИНА ТА КАВА', 'ДЕСЕРТ НА ВИБІР']},
    },
]

TESTI = {
    "storia": {
        "it": ['Questa storia comincia molto prima di noi.', 'Comincia con una porta di ferro battuto ben più antica del 1855, l’anno che racconta la nostra fondazione. Un’insegna dipinta con la vecchia dicitura “Antica Trattoria dei Tre Gobbi”, coi tre gobbetti paffuti e sorridenti, appesa in via Broseta da quando nel cortile sostavano diligenze, carri e viaggiatori. Dietro il bancone c’era Michele Bettinelli, oste piccolo e rubicondo, amico d’infanzia del famoso compositore Gaetano Donizetti — che appena poteva tornava fin qui per una polenta come si deve e una serata tra amici veri.', 'Dal 1855 questa insegna non ha mai smesso di accendersi. Sono passate generazioni di osti, due guerre, e Bergamo è cambiata mille volte. I tre gobbi sono sempre qui.', 'Nel settembre del 2017 ho varcato quella porta anch’io; l’anno dopo è toccato a me. Non si “compra” un posto così: se ne diventa custodi. La promessa è semplice: materia prima delle nostre valli, ricette che parlano bergamasco e un posto dove si sta bene senza bisogno di effetti speciali. Sono l’oste e sono il cuoco — ma un’osteria non si guida solo dai fornelli, e quindi mi troverete sempre più spesso anche tra i tavoli, a raccontarvi i piatti. Con me c’è una famiglia intera, dentro e fuori dalla cucina: a partire da mamma Antonella e papà Gerry, che ogni giorno chiudono a mano i nostri casoncelli.'],
        "en": ['This story begins long before us.', 'It begins with a wrought-iron door far older than 1855, the year we give as our founding. With a hand-painted sign bearing the old name “Antica Trattoria dei Tre Gobbi” and its three plump, smiling hunchbacks, hanging in via Broseta since the days when stagecoaches, carts and travellers pulled into the courtyard. Behind the counter stood Michele Bettinelli, a short, ruddy-faced innkeeper and childhood friend of the great composer Gaetano Donizetti — who came back here whenever he could for a proper polenta and an evening among real friends.', 'Since 1855 that sign has never once gone dark. Generations of innkeepers have come and gone, two wars have passed, and Bergamo has changed a thousand times over. The three hunchbacks are still here.', 'In September 2017 I walked through that door myself; a year later it was my turn. You don’t “buy” a place like this: you become its keeper. The promise is a simple one — ingredients from our valleys, recipes that speak Bergamasque, and somewhere you feel at ease with no need for special effects. I am the <i>oste</i> and I am the cook, but an osteria isn’t run from the stove alone, so you will find me more and more often among the tables too, telling you about the dishes. There is a whole family with me, in the kitchen and out of it, starting with mamma Antonella and papà Gerry, who seal our casoncelli by hand every day.'],
        "fr": ['Cette histoire commence bien avant nous.', 'Elle commence par une porte en fer forgé bien plus ancienne que 1855, l’année que l’on donne pour celle de notre fondation. Par une enseigne peinte à la main portant l’ancien nom «\xa0Antica Trattoria dei Tre Gobbi\xa0», avec ses trois bossus dodus et souriants, accrochée via Broseta depuis l’époque où diligences, charrettes et voyageurs faisaient halte dans la cour. Derrière le comptoir se tenait Michele Bettinelli, aubergiste petit et rubicond, ami d’enfance du célèbre compositeur Gaetano Donizetti — qui revenait ici dès qu’il le pouvait pour une polenta comme il faut et une soirée entre vrais amis.', 'Depuis 1855, cette enseigne ne s’est jamais éteinte. Des générations d’aubergistes se sont succédé, deux guerres sont passées, et Bergame a changé mille fois. Les trois bossus, eux, sont toujours là.', 'En septembre 2017, j’ai franchi cette porte moi aussi\xa0; un an plus tard, ce fut mon tour. Un endroit pareil, on ne l’«\xa0achète\xa0» pas\xa0: on en devient le gardien. La promesse est simple — les produits de nos vallées, des recettes qui parlent bergamasque, et un lieu où l’on se sent bien sans avoir besoin d’effets spéciaux. Je suis l’<i>oste</i> et je suis le cuisinier, mais une osteria ne se dirige pas seulement depuis les fourneaux\xa0: vous me trouverez donc de plus en plus souvent en salle aussi, à vous raconter les plats. Avec moi, il y a toute une famille, en cuisine et en dehors, à commencer par maman Antonella et papa Gerry, qui ferment nos casoncelli à la main, chaque jour.'],
        "es": ['Esta historia empieza mucho antes que nosotros.', 'Empieza con una puerta de hierro forjado muy anterior a 1855, el año que damos como el de nuestra fundación. Con un letrero pintado a mano con el viejo nombre «Antica Trattoria dei Tre Gobbi», con los tres jorobaditos rollizos y sonrientes, colgado en la via Broseta desde los tiempos en que el patio acogía diligencias, carros y viajeros. Tras el mostrador estaba Michele Bettinelli, tabernero bajito y rubicundo, amigo de la infancia del célebre compositor Gaetano Donizetti, que en cuanto podía volvía hasta aquí por una polenta como Dios manda y una noche entre amigos de verdad.', 'Desde 1855 este letrero no ha dejado de encenderse ni una sola vez. Han pasado generaciones de taberneros, dos guerras, y Bérgamo ha cambiado mil veces. Los tres jorobados siguen aquí.', 'En septiembre de 2017 crucé yo también aquella puerta; un año después me tocó a mí. Un sitio así no se «compra»: uno se convierte en su guardián. La promesa es sencilla: materia prima de nuestros valles, recetas que hablan bergamasco y un lugar donde se está bien sin necesidad de efectos especiales. Soy el <i>oste</i> y soy el cocinero, pero una osteria no se lleva solo desde los fogones, así que cada vez me encontrarás más a menudo también entre las mesas, contándote los platos. Conmigo hay una familia entera, dentro y fuera de la cocina, empezando por mamá Antonella y papá Gerry, que cada día cierran a mano nuestros casoncelli.'],
        "de": ['Diese Geschichte beginnt lange vor uns.', 'Sie beginnt mit einer schmiedeeisernen Tür, die weit älter ist als 1855 – das Jahr, das wir als unser Gründungsjahr angeben. Mit einem handgemalten Schild, das den alten Namen „Antica Trattoria dei Tre Gobbi“ trägt, mit den drei rundlichen, lächelnden Buckligen – es hängt in der Via Broseta, seit im Hof noch Kutschen, Karren und Reisende Halt machten. Hinter dem Tresen stand Michele Bettinelli, ein kleiner, rotbackiger Wirt und Jugendfreund des berühmten Komponisten Gaetano Donizetti – der, wann immer er konnte, hierher zurückkam, für eine anständige Polenta und einen Abend unter echten Freunden.', 'Seit 1855 hat dieses Schild nie aufgehört zu leuchten. Generationen von Wirten sind gekommen und gegangen, zwei Kriege sind über das Land hinweggezogen, und Bergamo hat sich tausendmal verändert. Die drei Buckligen sind immer noch da.', 'Im September 2017 bin auch ich durch diese Tür getreten; ein Jahr später war ich an der Reihe. Einen solchen Ort „kauft“ man nicht: man wird sein Hüter. Das Versprechen ist einfach – Zutaten aus unseren Tälern, Rezepte, die Bergamaskisch sprechen, und ein Ort, an dem man sich wohlfühlt, ganz ohne Spezialeffekte. Ich bin der <i>Oste</i> und ich bin der Koch, aber eine Osteria führt man nicht allein vom Herd aus, und deshalb werden Sie mich immer öfter auch zwischen den Tischen finden, wo ich Ihnen von den Gerichten erzähle. Mit mir ist eine ganze Familie da, in der Küche und außerhalb: angefangen bei Mamma Antonella und Papà Gerry, die jeden Tag unsere Casoncelli von Hand schließen.'],
        "uk": ['Ця історія почалася задовго до нас.', 'Вона почалася з кованих залізних дверей, значно давніших за 1855 рік — рік, який ми вважаємо роком свого заснування. З мальованої вивіски зі старою назвою «Antica Trattoria dei Tre Gobbi» і трьома пухкенькими усміхненими горбанями, що висить на віа Бросета ще відтоді, коли на подвір’ї спинялися диліжанси, вози й мандрівники. За шинквасом стояв Мікеле Беттінеллі — невисокий рум’яний шинкар, друг дитинства славетного композитора Гаетано Доніцетті, який щоразу, коли міг, повертався сюди по справжню поленту й вечір серед справжніх друзів.', 'Від 1855 року ця вивіска не згасала жодного разу. Змінилися покоління господарів, минули дві війни, Бергамо змінилося тисячу разів. Три горбані досі тут.', 'У вересні 2017 року цей поріг переступив і я; наступного року надійшла моя черга. Таке місце не «купують» — його стають хранителями. Обіцянка проста: продукти з наших долин, рецепти, що говорять бергамською, і місце, де добре без жодних спецефектів. Я — <i>oste</i>, і я ж кухар; але остерією керують не лише від плити, тож дедалі частіше ви бачитимете мене й між столами, де я розповідатиму вам про страви. Зі мною ціла родина, на кухні й поза нею: починаючи від мами Антонелли й тата Джеррі, які щодня зліплюють руками наші casoncelli.'],
    },
    "storia_chiusa": {
        "it": ['Benvenuti.', 'Siete a casa.'],
        "en": ['Welcome.', 'You’re home.'],
        "fr": ['Bienvenue.', 'Vous êtes chez vous.'],
        "es": ['Bienvenido.', 'Aquí estás en casa.'],
        "de": ['Herzlich willkommen.', 'Sie sind hier zu Hause.'],
        "uk": ['Ласкаво просимо.', 'Ви вдома.'],
    },
    "storia_firma": {
        "it": 'Marco, l’oste e cuoco.',
        "en": 'Marco, the oste and the cook.',
        "fr": 'Marco, l’oste et le cuisinier.',
        "es": 'Marco, el oste y cocinero.',
        "de": 'Marco, der Oste und Koch.',
        "uk": 'Марко, oste і кухар.',
    },
    "foto_didascalia": {
        "it": 'L’osteria nel 1907',
        "en": 'The osteria in 1907',
        "fr": 'L’osteria en 1907',
        "es": 'La osteria en 1907',
        "de": 'Die Osteria im Jahr 1907',
        "uk": 'Остерія у 1907 році',
    },
    "allergeni": {
        "it": 'IL NOSTRO PERSONALE È PREPARATO A RISPONDERVI SU ALLERGENI ED INTOLLERANZE.',
        "en": 'OUR STAFF ARE HAPPY TO ANSWER ANY QUESTION ABOUT ALLERGENS AND INTOLERANCES.',
        "fr": 'NOTRE PERSONNEL EST FORMÉ POUR RÉPONDRE À TOUTE QUESTION SUR LES ALLERGÈNES ET LES INTOLÉRANCES.',
        "es": 'NUESTRO PERSONAL ESTÁ PREPARADO PARA RESPONDERTE SOBRE ALÉRGENOS E INTOLERANCIAS.',
        "de": 'UNSER PERSONAL BEANTWORTET IHNEN GERNE ALLE FRAGEN ZU ALLERGENEN UND UNVERTRÄGLICHKEITEN.',
        "uk": 'НАШ ПЕРСОНАЛ ГОТОВИЙ ВІДПОВІСТИ НА ВАШІ ЗАПИТАННЯ ПРО АЛЕРГЕНИ ТА ХАРЧОВУ НЕПЕРЕНОСИМІСТЬ.',
    },
    "bambini_titolo": {
        "it": 'MENÙ BAMBINI',
        "en": 'CHILDREN’S MENU',
        "fr": 'MENU ENFANTS',
        "es": 'MENÚ INFANTIL',
        "de": 'KINDERMENÜ',
        "uk": 'ДИТЯЧЕ МЕНЮ',
    },
    "bambini_sotto": {
        "it": 'DISPONIBILE SU RICHIESTA.',
        "en": 'AVAILABLE ON REQUEST.',
        "fr": 'DISPONIBLE SUR DEMANDE.',
        "es": 'DISPONIBLE BAJO PETICIÓN.',
        "de": 'AUF ANFRAGE ERHÄLTLICH.',
        "uk": 'ЗА ЗАПИТОМ.',
    },
    "bambini_righe": {
        "it": [('PRIMO PIATTO', '10 EURO'), ('SECONDO PIATTO', '15 EURO')],
        "en": [('FIRST COURSE', '10 EUROS'), ('MAIN COURSE', '15 EUROS')],
        "fr": [('PREMIER PLAT', '10 EUROS'), ('PLAT PRINCIPAL', '15 EUROS')],
        "es": [('PRIMER PLATO', '10 EUROS'), ('SEGUNDO PLATO', '15 EUROS')],
        "de": [('ERSTER GANG', '10 EURO'), ('HAUPTGANG', '15 EURO')],
        "uk": [('ПЕРША СТРАВА (ПАСТА АБО РИЗОТО)', '10 ЄВРО'), ('ОСНОВНА СТРАВА', '15 ЄВРО')],
    },
    "bevande": {
        "it": [('TÈ E TISANE', '10', None), ('ESPRESSO', '3', None), ('MOKA “PUMP”', '10', 'DEGUSTAZIONE PER DUE'), ('ACQUA', '3', None), ('COPERTO', '5', None)],
        "en": [('TEA AND HERBAL TEAS', '10', None), ('ESPRESSO', '3', None), ('MOKA “PUMP”', '10', 'TASTING FOR TWO'), ('WATER', '3', None), ('COVER CHARGE', '5', None)],
        "fr": [('THÉS ET TISANES', '10', None), ('ESPRESSO', '3', None), ('MOKA «\xa0PUMP\xa0»', '10', 'DÉGUSTATION POUR DEUX'), ('EAU', '3', None), ('COUVERT', '5', None)],
        "es": [('TÉS E INFUSIONES', '10', None), ('ESPRESSO', '3', None), ('MOKA «PUMP»', '10', 'DEGUSTACIÓN PARA DOS'), ('AGUA', '3', None), ('CUBIERTO', '5', None)],
        "de": [('TEE UND KRÄUTERTEES', '10', None), ('ESPRESSO', '3', None), ('MOKA „PUMP“', '10', 'VERKOSTUNG FÜR ZWEI'), ('WASSER', '3', None), ('GEDECK', '5', None)],
        "uk": [('ЧАЙ І ТРАВ’ЯНІ НАСТОЇ', '10', None), ('ЕСПРЕСО', '3', None), ('МОКА «PUMP»', '10', 'ДЕГУСТАЦІЯ НА ДВОХ'), ('ВОДА', '3', None), ('КУВЕРТ (СЕРВІРУВАННЯ)', '5', None)],
    },
    "legenda": {
        "it": [('V', 'VEGETARIANO'), ('VG', 'VEGANO'), ('NG', 'NO GLUTINE'), ('NL', 'NO LATTOSIO'), ('ONL', 'OPZIONE NO LATTOSIO'), ('OV', 'OPZIONE VEGETARIANA'), ('OVG', 'OPZIONE VEGANA'), ('ONG', 'OPZIONE NO GLUTINE')],
        "en": [('V', 'VEGETARIAN'), ('VG', 'VEGAN'), ('GF', 'GLUTEN FREE'), ('LF', 'LACTOSE FREE'), ('LFO', 'LACTOSE-FREE OPTION'), ('VO', 'VEGETARIAN OPTION'), ('VGO', 'VEGAN OPTION'), ('GFO', 'GLUTEN-FREE OPTION')],
        "fr": [('V', 'VÉGÉTARIEN'), ('VG', 'VÉGAN'), ('SG', 'SANS GLUTEN'), ('SL', 'SANS LACTOSE'), ('OSL', 'OPTION SANS LACTOSE'), ('OV', 'OPTION VÉGÉTARIENNE'), ('OVG', 'OPTION VÉGANE'), ('OSG', 'OPTION SANS GLUTEN')],
        "es": [('V', 'VEGETARIANO'), ('VG', 'VEGANO'), ('SG', 'SIN GLUTEN'), ('SL', 'SIN LACTOSA'), ('OSL', 'OPCIÓN SIN LACTOSA'), ('OV', 'OPCIÓN VEGETARIANA'), ('OVG', 'OPCIÓN VEGANA'), ('OSG', 'OPCIÓN SIN GLUTEN')],
        "de": [('V', 'VEGETARISCH'), ('VG', 'VEGAN'), ('GF', 'GLUTENFREI'), ('LF', 'LAKTOSEFREI'), ('LFO', 'AUF WUNSCH LAKTOSEFREI'), ('VO', 'AUF WUNSCH VEGETARISCH'), ('VGO', 'AUF WUNSCH VEGAN'), ('GFO', 'AUF WUNSCH GLUTENFREI')],
        "uk": [('В', 'ВЕГЕТАРІАНСЬКЕ'), ('ВГ', 'ВЕГАНСЬКЕ'), ('БГ', 'БЕЗ ГЛЮТЕНУ'), ('БЛ', 'БЕЗ ЛАКТОЗИ'), ('ОБЛ', 'МОЖЛИВО БЕЗ ЛАКТОЗИ'), ('ОВ', 'МОЖЛИВО ВЕГЕТАРІАНСЬКЕ'), ('ОВГ', 'МОЖЛИВО ВЕГАНСЬКЕ'), ('ОБГ', 'МОЖЛИВО БЕЗ ГЛЮТЕНУ')],
    },
    "sezioni_titoli": {
        "it": {'antipasti': 'ANTIPASTI', 'paste_risi_zuppe': 'PASTE, RISI E ZUPPE', 'piatti_del_giorno': 'PIATTI DEL GIORNO', 'contorni': 'CONTORNI', 'secondi': 'SECONDI', 'dolci': 'DOLCI', 'degustazioni': 'DEGUSTAZIONE', 'bambini': 'MENÙ BAMBINI'},
        "en": {'antipasti': 'STARTERS', 'paste_risi_zuppe': 'PASTA, RICE AND SOUPS', 'piatti_del_giorno': 'DISHES OF THE DAY', 'contorni': 'SIDES', 'secondi': 'MAIN COURSES', 'dolci': 'DESSERTS', 'degustazioni': 'TASTING MENU', 'bambini': 'CHILDREN’S MENU'},
        "fr": {'antipasti': 'ENTRÉES', 'paste_risi_zuppe': 'PÂTES, RIZ ET SOUPES', 'piatti_del_giorno': 'PLATS DU JOUR', 'contorni': 'ACCOMPAGNEMENTS', 'secondi': 'PLATS', 'dolci': 'DESSERTS', 'degustazioni': 'DÉGUSTATION', 'bambini': 'MENU ENFANTS'},
        "es": {'antipasti': 'ENTRANTES', 'paste_risi_zuppe': 'PASTAS, ARROCES Y SOPAS', 'piatti_del_giorno': 'PLATOS DEL DÍA', 'contorni': 'GUARNICIONES', 'secondi': 'SEGUNDOS', 'dolci': 'POSTRES', 'degustazioni': 'DEGUSTACIÓN', 'bambini': 'MENÚ INFANTIL'},
        "de": {'antipasti': 'VORSPEISEN', 'paste_risi_zuppe': 'PASTA, REIS UND SUPPEN', 'piatti_del_giorno': 'TAGESGERICHTE', 'contorni': 'BEILAGEN', 'secondi': 'HAUPTGERICHTE', 'dolci': 'DESSERTS', 'degustazioni': 'DEGUSTATIONSMENÜ', 'bambini': 'KINDERMENÜ'},
        "uk": {'antipasti': 'ЗАКУСКИ', 'paste_risi_zuppe': 'ПАСТА, РИЗОТО ТА СУПИ', 'piatti_del_giorno': 'СТРАВИ ДНЯ', 'contorni': 'ГАРНІРИ', 'secondi': 'ОСНОВНІ СТРАВИ', 'dolci': 'ДЕСЕРТИ', 'degustazioni': 'ДЕГУСТАЦІЯ', 'bambini': 'ДИТЯЧЕ МЕНЮ'},
    },
}

